### ISSUE TITLE
How to add fluid animation to my Notion Page

### ISSUE THREAD

**Issue by sanyogthescholar** [transitive-bullshit/nextjs-notion-starter-kit#108]
Hi, I checked out your site https://transitivebullsh.it/ and the fluid animation was really eye catching. Could you please let me know how I can add it to my own Notion page? I believe you are using your [react-fluid-animation](https://github.com/transitive-bullshit/react-fluid-animation) package, right?

Your Notion page has a static image, yet your published website has the fluid animation. Can you please explain how you did this?
Thank you!

**Comment by transitive-bullshit** [comment]
Hey @sanyogthescholar, check out the [branch](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/tree/transitive-bullshit) on this repo which I use for my custom site.

It's 99% the same as the normal template, but has a few extras for things like the fluid animation.

Here's the diff: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/compare/transitive-bullshit

**Comment by sanyogthescholar** [comment]
Thank you very much, that clears it up!

Also can you please explain how you got the workspace ID? When I pause the script and see the global variables, these are the only ones I get. I cannot find the block variable

![image](https://user-images.githubusercontent.com/50242941/117007391-39bd0f80-ad07-11eb-8359-e43299e79a9d.png)

Or should I open a new issue for this?

**Comment by transitive-bullshit** [comment]
Open your devtools and type `block.space_id`. You shouldn't need to use the script debugger.

**Comment by sanyogthescholar** [comment]
Sorry but I have tried that too and it didn't work. Here is what I get:
![image](https://user-images.githubusercontent.com/50242941/117107726-b00d5080-ad9f-11eb-99f8-34f9453fbd28.png)
