### ISSUE TITLE
'block' is not defined while trying to retrieve Notion Workspace ID

### ISSUE THREAD

**Issue by sanyogthescholar** [transitive-bullshit/nextjs-notion-starter-kit#111]
I tried retrieving the block.space_id but here is what I get in the Chrome console

![image](https://user-images.githubusercontent.com/50242941/117107726-b00d5080-ad9f-11eb-99f8-34f9453fbd28.png)

I tried using the debugger but that too did not work

![image2](https://user-images.githubusercontent.com/50242941/117007391-39bd0f80-ad07-11eb-8359-e43299e79a9d.png)

Here is my public Notion page:
https://www.notion.so/2aff6f7db5f64da98bf8f6902f53ca5c

**Comment by transitive-bullshit** [comment]
You need to do it from a page hosted via this starter kit. For example, https://react-notion-x-demo.transitivebullsh.it/2aff6f7db5f64da98bf8f6902f53ca5c

Your workspace ID is `4bf2c35d-acbb-450a-9f7a-e1b0a89e8871`
