### ISSUE TITLE
Build completely static pages

### ISSUE THREAD

**Issue by tiulpin** [transitive-bullshit/nextjs-notion-starter-kit#114]
Hi! 
I was wondering if it's possible to build static pages and generate og image with next.js -> then they could be uploaded on any hosting, even one without serverless functions.

How one could do that?

Thanks.

**Comment by transitive-bullshit** [comment]
Check out https://nextjs.org/docs/advanced-features/static-html-export

Aside from this option, this boilerplate is optimized for Next.js and Vercel.

Other use cases are outside the scope of this project.

**Comment by tiulpin** [comment]
Thanks!
