### ISSUE TITLE
Integrating the existing app with new notion API

### ISSUE THREAD

**Issue by jerryyangboyu** [transitive-bullshit/nextjs-notion-starter-kit#115]
Notion has released it own API on 13th, May, providing official way to access the user's content using the notion integration. So there are no needs for reverse engineering on existing frameworks.
For more details, see [https://developers.notion.com/](https://developers.notion.com/).
For notion integration, see [Add and manage integrations with the API](https://www.notion.so/Add-and-manage-integrations-with-the-API-910ac902372042bc9da38d48171269cd)

**Comment by ricardowangjie** [comment]
Yes

**Comment by MichaelDevC** [comment]
This needs to be done in [React-Notion-X](https://github.com/NotionX/react-notion-x). This is a template based on that package

**Comment by AlainRo** [comment]
The Notion API is still incomplete. Images for examples cannot be retrieved. Not usable at this time. Thank you for the unofficial way to do it.

**Comment by transitive-bullshit** [comment]
Tracking this in https://github.com/NotionX/react-notion-x/issues/66. See https://github.com/NotionX/react-notion-x/issues/228 for a proposal
