### ISSUE TITLE
trouble getting utterances set up

### ISSUE THREAD

**Issue by xyfx666** [transitive-bullshit/nextjs-notion-starter-kit#117]
I configure it like this, but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/51446918/119013135-49a44700-b9c9-11eb-9b4f-327436e364de.png)

https://blog.xyfx666.top/

**Comment by transitive-bullshit** [comment]
You need two repos for utterances to work. This is likely a config issue on your end.

For a working example, check out https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/transitive-bullshit/site.config.js#L37 and the corresponding repo https://github.com/transitive-bullshit/transitivebullsh.it

**Comment by transitive-bullshit** [comment]
Utterances has been removed in the latest release. I decided to simplify things since it wasn't seeing much usage.

**Comment by wyk111wyk** [comment]
> Utterances has been removed in the latest release. I decided to simplify things since it wasn't seeing much usage.

That's not true, don't you guys think a blog without comments and replies feels so lonely?

**Comment by transitive-bullshit** [comment]
@wyk111wyk agreed, but it's even more lonely when there are zero comments and replies everywhere 😂 

Hahaha in all seriousness though, I've been considering adding https://github.com/giscus/giscus support. Thoughts?

**Comment by wyk111wyk** [comment]
@transitive-bullshit Leave a choice is always good, in addition giscus does look more promising.

**Comment by sgamerw** [comment]
> @wyk111wyk agreed, but it's even more lonely when there are zero comments and replies everywhere 😂
> 
> Hahaha in all seriousness though, I've been considering adding https://github.com/giscus/giscus support. Thoughts?

@transitive-bullshit that's nice, so when will you add giscus support 😁
