### ISSUE TITLE
trouble when login github for comments in my blog

### ISSUE THREAD

**Issue by zjuzhfbloodz** [transitive-bullshit/nextjs-notion-starter-kit#120]
my blog: https://perfectstranger.me/
when login github account I got a error 1101 from cloudflare
![image](https://user-images.githubusercontent.com/60741747/119608606-d2d3d780-be28-11eb-94f3-43f1da5029dc.png)
![image](https://user-images.githubusercontent.com/60741747/119608633-dc5d3f80-be28-11eb-90a8-dc88cb295a9a.png)
and I don't know how to fix it. I'm totally new for web development and wish your answer!

**Comment by transitive-bullshit** [comment]
Utterances has been removed in the latest release. I decided to simplify things since it wasn't seeing much usage.

**Comment by shenoynikhil** [comment]
How can I configure Utterances?
