### ISSUE TITLE
Search indexing for notion notes not working even after vercel deploy

### ISSUE THREAD

**Issue by Visakh47** [transitive-bullshit/nextjs-notion-starter-kit#123]
This is the link to the public notion page: https://www.notion.so/Techno-Blogs-b4ca1412d96b4787a5659c16dccc63af

I'd also like to thank you for creating this wonderful repository! You have done a splendid job making it usable and accessible for everyone :)

**Comment by Visakh47** [comment]
![image](https://user-images.githubusercontent.com/64662344/121994417-dec90e80-cdc2-11eb-95b5-d45c96ec96f0.png)
Even after waiting more than 5 minutes , no search results have been generated

**Comment by Ashinch** [comment]
me too, I checked Chrome Network panel, and the search API is CORS, but I see the author's blog is called normally. I checked a lot of code (like token), but it still didn't work, I also hope to get a solution.

**Comment by Visakh47** [comment]
![image](https://user-images.githubusercontent.com/64662344/122088910-d9e87700-ce23-11eb-8d0b-cbc24077f480.png)



Hey @Ashinch, I figured it out. Initially, (for some reason) my block space id was wrong, I updated it just now, and the search API started working, the CORS origin error was no longer seen. 

Also in the site.config.js, try to mention your correct domain name - the one you've deployed as production using vercel. Although that wasn't the reason for my error - I mentioned it for future checkers having a similar issue.

**Comment by Ashinch** [comment]
@Visakh47 Thank you very much for your reply, I will try it tomorrow! 😃

**Comment by Ashinch** [comment]
> @Visakh47 Thank you very much for your reply, I will try it tomorrow! 😃

@Visakh47 Thanks again, I have solved the problem. My request for `*.com` on vercel is redirected to `www.*.com`, but the domain I configured in `site.config.js` does not have `www`. When I add `www` After the search API can be used normally.

**Comment by Visakh47** [comment]
Welcome, @Ashinch! , will close the issue now!

**Comment by YamenSharaf** [comment]
> > @Visakh47 Thank you very much for your reply, I will try it tomorrow! 😃
> 
> @Visakh47 Thanks again, I have solved the problem. My request for `*.com` on vercel is redirected to `www.*.com`, but the domain I configured in `site.config.js` does not have `www`. When I add `www` After the search API can be used normally.

Thank you for clarifying this. I was stuck and now unstuck 🙏🏻
