### ISSUE TITLE
Page Default to dark mode?

### ISSUE THREAD

**Issue by nehakumarisaa** [transitive-bullshit/nextjs-notion-starter-kit#125]
Hi Travis,
Thanks for putting this up. 
Amazed to see the amount of customization I can do with this. 

I wanted to default my page to the dark mode and switch to light on toggle. 
I tried updating the following line in NotionPage.tsx:
const darkMode = useDarkMode(false, { classNameDark: 'dark-mode' })

Updated false to true. On doing this, it started with the dark mode, but the dark mode css formatting went for a toss.
Can you please help me with this? 

Thanks,
Neha

**Comment by Visakh47** [comment]
@nehakumarisaa , I believe changing the preferDarkQuery to light, should do the trick!
here's the change I made for reference : 
https://github.com/Visakh47/TechnoBlogs/commit/fa68e5b86fc2db97b17d8e6883bf881270742e48

**Comment by transitive-bullshit** [comment]
Thanks @Visakh47; yep, that's the easiest way to do what you're looking for.

**Comment by nehakumarisaa** [comment]
Thank you @transitive-bullshit @Visakh47. The solution worked for me!!! :)
