### ISSUE TITLE
Is the website automatically updating?

### ISSUE THREAD

**Issue by marsrobertson** [transitive-bullshit/nextjs-notion-starter-kit#129]
Related: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/76

> Fork / clone this repo
> Change a few values in site.config.js
> npm install
> npm run dev to test locally
> npm run deploy to deploy to vercel 💪

It remains unclear to me whether it will update as I make changes on Notion?

**Comment by MichaelDevC** [comment]
I'm making my own template by starting from this. It will automatically update the page content when you deploy in Vercel. To update the pages list, or what pages are in your Notion space, you need to re-deploy the project.

**Comment by GoByeBye** [comment]
> Related: #76
> 
> > Fork / clone this repo
> > Change a few values in site.config.js
> > npm install
> > npm run dev to test locally
> > npm run deploy to deploy to vercel 💪
> 
> It remains unclear to me whether it will update as I make changes on Notion?

From what I've seen so far you can force an update by using the search function and typing in the page name. Outside of that I've noticed it's updated automatically but I have no idea at what interval this happens

**Comment by emindeniz99** [comment]
It will update incrementally every 10 seconds for new requests. You can modify it.
https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/1d19cd0d6c20e570d7db31557a350e38e23a215e/pages/%5BpageId%5D.tsx#L21

You can check this next.js feature https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration
