### ISSUE TITLE
How to correct ESM error with microbundle ?

### ISSUE THREAD

**Issue by Kaeldyr** [transitive-bullshit/nextjs-notion-starter-kit#137]
Hi Guys,

Sorry if the question is a bit stupid (I have only small bases in programming), I try to install the starter kit, but I still have an ESM error when I want to run the script.

`Error: Must use import to load ES Module: C:\Users\jerem\blog\nextjs-notion-starter-kit-main\node_modules\unist-util-visit\index.js
require() of ES modules is not supported.
require() of C:\Users\jerem\blog\nextjs-notion-starter-kit-main\node_modules\unist-util-visit\index.js from C:\Users\jerem\blog\nextjs-notion-starter-kit-main\node_modules\static-tweets\build\cjs\markdown\rehype-tweet.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\jerem\blog\nextjs-notion-starter-kit-main\node_modules\unist-util-visit\package.json.`

In an another issue, I found the nickrttn solution ([here, microbundle](https://github.com/transitive-bullshit/react-static-tweets/pull/34)), but I have to admit that I don't find how to use it to correct the problem. I tried to replace some files in node-module folder, had a look on different package.json files but as I'm not familiar with React, I didn't find the solution.

Can I have some help with that ?
Thanks a lot.

**Comment by transitive-bullshit** [comment]
This solution has been incorporated into the latest release. Thanks :)
