### ISSUE TITLE
Add copy button to the notion-code-block

### ISSUE THREAD

**Issue by yymmm9** [transitive-bullshit/nextjs-notion-starter-kit#148]
I would love having the possibility to copy the text/code contained in the block for both mobile an desktop users, just like the notion UI 👇

![image](https://user-images.githubusercontent.com/46626991/129620890-551a1410-08dc-4d15-9701-f710f9f762c5.png)

**Comment by transitive-bullshit** [comment]
Done https://github.com/NotionX/react-notion-x/pull/239
