### ISSUE TITLE
Image Upload Crashes Page Load

### ISSUE THREAD

**Issue by pavlovcik** [transitive-bullshit/nextjs-notion-starter-kit#151]
I noticed this while writing an update a few days ago and after finishing my article I tried pushing to Vercel and loading from the site. It kept crashing - looks like this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/130119105-be92a7eb-78f1-4830-b9b2-c465f850e2c6.png">
(this is me reproducing the issue locally to write this issue faster.)

I tested again today uploading this lovely picture of Zak and it still appears to be an issue.
<img width="1440" alt="Screen Shot 2021-08-19 at 13 48 44" src="https://user-images.githubusercontent.com/4975670/130118849-b1bfed52-350a-4293-bd74-94c2fa52abf8.png">

https://ubiquitydao.notion.site/Q4-Plans-August-Update-873b09a0475f4df187e0d4827563ecc4
https://dao.ubq.fi/Q4-Plans-August-Update

P.S.

When I try going to the url of any of these images (e.g. https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b0b41951-e997-481f-bcdb-86bfaadcdf04/e88278c519b68a0a1edba6daa678f596.webp) there's an AWS permissions error not sure if relevant.

P.P.S. Have not tested this extensively but it feels like the last week or so the only time the site refetches the notion content is when I redeploy on Vercel :(

**Comment by pavlovcik** [comment]
I think my uploads were ultra slow. My colleague asked me to try again and I left my notion and walked away for an hour. I realized that the page loads now! 

It would be nice to have a handler for this, where it could detect the missing or blocked image and simply render an icon that represents a broken link etc. instead of crashing the page.

**Comment by transitive-bullshit** [comment]
This should be resolved in the latest release.
