### ISSUE TITLE
Bug the titles of the columns  for tables

### ISSUE THREAD

**Issue by AntonioDEM** [transitive-bullshit/nextjs-notion-starter-kit#158]
I'm trying to build a small blog, but I ran into a more awkward BUG. At first I thought it was my problem due to inexperience in programming, but later I realized that it is a potential bug in the script that should be fixed. below I insert an example with two images, respectively the image of Notion and the image that you should see Online. really bad.

<a href="https://ibb.co/cLHbXJT"><img src="https://i.ibb.co/Rymh42H/Scr-2021-09-28-alle-06-05-27.png" alt="Notion Image" border="0"></a><br /><a target='_blank' href='https://i.ibb.co/Rymh42H/Scr-2021-09-28-alle-06-05-27.png'>Notion Image</a><br />

in the first image you can see the titles of the columns, which disappear successively.

<a href="https://ibb.co/XsGsNF6"><img src="https://i.ibb.co/J7S70r8/Scr-2021-09-28-alle-06-08-43.png" alt="On-Line Image" border="0"></a><br /><a target='_blank' href='https://it.imgbb.com/'>On-Line Image" </a><br />

Are there any solutions to this?

**Comment by AntonioDEM** [comment]
I have found a possible solution to the problem.

on /style/notion.css I added:

```
.notion-collection-column-title {
	-webkit-user-select: hidden;
    -ms-user-select: hidden;
    user-select: hidden;
    display: flex;
	align-items: center;
	margin-bottom: 1px;
    width: 100%;
    height: 100%;
    padding-left: 18px; /*sposta titoli colonne*/
    padding-right: 18px;
    border-right: 0px solid var(--fg-color-10);
	text-align: left;
	overflow: hidden
	/* justify-content: center; */
	/* border-radius: 14px;
	box-shadow: 1px 1px 1px 1px rgba(15, 15, 15, 0.1); */
  }

  .notion-collection-row-property .notion-property {
	-webkit-user-select: hidden;
    transition: background 20ms ease-in;
    cursor: pointer;
    display: flex;
    align-items: center;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    border-bottom-right-radius: 3px;
    border-bottom-left-radius: 3px;
    width: 100%;
    min-height: 14px;
    padding: 6px 8px 7px;
    font-size: 14px;
    overflow: hidden;
  }
```

<a href="https://ibb.co/5r7fJpG"><img src="https://i.ibb.co/VgKPknJ/Scr-2021-09-28-alle-22-40-50.png" alt="Scr-2021-09-28-alle-22-40-50" border="0"></a>

**Comment by transitive-bullshit** [comment]
This looks like a bug in `react-notion-x` which is maintained separately from this project (it's the underlying notion rendering engine).

Please open a corresponding issue over there.

Thanks for the report & sorry you're running into issues, but there are more maintainers of `react-notion-x` so hopefully it'll be solved over there.
