### ISSUE TITLE
Vercel app not updating

### ISSUE THREAD

**Issue by g-tejas** [transitive-bullshit/nextjs-notion-starter-kit#184]
Whenever i make changes to my notion, from the Notion app, the front page seems to update but the rest of the subpages do not automatically update. I need to manually push code to make sure the website updates, am I doing anything wrong? Hope to hear from you

**Comment by XahidEx** [comment]
Bro, Try refreshing your site 2-5 times. It always works. 😊

**Comment by g-tejas** [comment]
I tried, but it still doesnt seem to work, I have reset my cache as well

**Comment by transitive-bullshit** [comment]
Closing as stale.

There are definitely some large fixes in the latest release that could help with your issue.
