### ISSUE TITLE
TOC not show

### ISSUE THREAD

**Issue by Kherrisan** [transitive-bullshit/nextjs-notion-starter-kit#185]
Hi, I'm new to this blog framework. The UI of home page is quite attractive. 
But I come into the issue that the table of contents doesn't show as expected. I have deployed the code to the Vercel.
[Vercel Page](https://blog-mu-lime.vercel.app/b6cb4612f0d34dcfb527d46c1e0bdd82)
[Notion Page](https://www.notion.so/kherrisan/b6cb4612f0d34dcfb527d46c1e0bdd82)
[Code Repository](https://github.com/Kherrisan/blog)
Would you please help me check what's wrong?

**Comment by HandanYU** [comment]
I have the same problem. I also found that the table of contents which is put on the top of the page can show, while if it would be put at the left hand, it would not show again. Additionally, how can I use scroll table of contents just like 'get-page-table-of-contents.ts' you written in another project? Thanks

**Comment by frankcbliu** [comment]
you can see the code of [NotionPage.tsx](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx)
here: 
![image](https://user-images.githubusercontent.com/36353894/145681314-61422943-c822-4197-b50c-0479a44f6d6b.png)
it limit only the parent-page-type is collection, so a easy way to fix it is to change it to :
```
  const isBlogPost =
    block.type === 'page' &&
    (block.parent_table === 'block' || block.parent_table === 'collection')
``` 

i also create a version of notion-blog base on this, you also can see in: [awesome-nextjs-notion-blog](https://github.com/frankcbliu/awesome-nextjs-notion-blog)

**Comment by transitive-bullshit** [comment]
1. make sure you're on a page where `showTableOfContents` is set to `true`
2. make sure the page has at least `minTableofContentsItems` headers
3. make sure you're viewing on a browser wide enough to display the toc

**Comment by 0x5a57** [comment]
under fullpage will the toc be automatically generated
```
<NotionRenderer
  recordMap={recordMap}
  showTableOfContents={true}
  minTableOfContentsItems={3}
  fullPage={true}  // notice this property
/>
```
