### ISSUE TITLE
plan to support Simple Table

### ISSUE THREAD

**Issue by cailurus** [transitive-bullshit/nextjs-notion-starter-kit#193]
Simple Table is a new lightweight feature in Notion, any plan to support?

**Comment by chiperman** [comment]
> Maybe not so easy 😅 You need also to update the following to avoid issues:
> 
> ```
> yarn add notion-client@latest
> yarn add notion-types@latest
> yarn add notion-utils@latest
> ```

Hi, is there any tutorial to show how to upgrade dependencies you mentioned?

**Comment by julbrs** [comment]
> Hi, is there any tutorial showing how to upgrade dependencies you mentioned above?

No. But you can get a look at my fork with correct dependencies:

https://github.com/julbrs/julbrs-portfolio/blob/main/package.json

**Comment by chiperman** [comment]
> > Hi, is there any tutorial showing how to upgrade dependencies you mentioned above?
> 
> No. But you can get a look at my fork with correct dependencies:
> 
> [https://github.com/julbrs/julbrs-portfolio/blob/main/package.json](https://github.com/julbrs/julbrs-portfolio/blob/main/package.json?rgh-link-date=2022-02-22T22%3A14%3A09Z)

Thank you, I will review and look carefully at your repo but I have one more question, can you help me to know how you make this page https://sidoine.org/outdoor. I have a second page want to make in the blog but it can only show **Table** in it, however, your blog about /Outdoor can show the Gallery, did you do some DIY in the CSS or something?
<img width="1060" alt="截屏2022-02-23 上午9 39 53" src="https://user-images.githubusercontent.com/34889778/155248593-1e53c66e-f357-4fa4-b01f-f9400c1523e9.png">

**Comment by julbrs** [comment]
Hello!
No trick, it's just a database with a gallery view here 😇
![image](https://user-images.githubusercontent.com/4988590/155249175-2c876864-bfb2-4962-8a5c-1eab526f69ac.png)

**Comment by chiperman** [comment]
> Hello! No trick, it's just a database with a gallery view here 😇 ![image](https://user-images.githubusercontent.com/4988590/155249175-2c876864-bfb2-4962-8a5c-1eab526f69ac.png)

Thank you so much, I'll try it again.

**Comment by chiperman** [comment]
@julbrs Hi, sorry to bother you, but when I merge some files of your repo to mine and I face some problems in the Vercel. I can't build it anymore. Can you help me?
```
Error occurred prerendering page "/balmuda-烤箱". Read more: https://nextjs.org/docs/messages/prerender-error
--
15:34:19.935 | TypeError: Cannot read property 'type' of undefined
15:34:19.935 | at getPageProperty (/vercel/path1/node_modules/notion-utils/build/cjs/get-page-property.js:13:50)
15:34:19.935 | at getPageDescription (/vercel/path1/.next/server/chunks/111.js:88:52)
15:34:19.935 | at NotionPage (/vercel/path1/.next/server/chunks/111.js:761:52)
15:34:19.935 | at d (/vercel/path1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
15:34:19.935 | at bb (/vercel/path1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
15:34:19.935 | at a.b.render (/vercel/path1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
15:34:19.935 | at a.b.read (/vercel/path1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
15:34:19.935 | at Object.exports.renderToString (/vercel/path1/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
15:34:19.935 | at Object.renderPage (/vercel/path1/node_modules/next/dist/server/render.js:596:45)
15:34:19.935 | at Function.getInitialProps (/vercel/path1/.next/server/chunks/859.js:603:19)
```

**Comment by julbrs** [comment]
HI @chiperman 

Can you share your repo? Thanks !

**Comment by chiperman** [comment]
@julbrs  This is the URL of my repo: https://github.com/chiperman/nextjs-notion-starter-kit.

**Comment by julbrs** [comment]
Hi, get a look at this commit: https://github.com/julbrs/julbrs-portfolio/commit/23ec2b3b6222f04eca1e04598c05193fd1ba8ce5

It seems that if there is no `Description` property on the page the build failed!

**Comment by chiperman** [comment]
Thanks for taking the time to help me, I have successfully built the whole project.

**Comment by transitive-bullshit** [comment]
I'm glad you guys figured it out. Thanks @julbrs 💪 

Planning to get a maintenance update out soon that will include all the latest packages.
