### ISSUE TITLE
Updated dependencies but Vercel Deployment failing

### ISSUE THREAD

**Issue by pHequals7** [transitive-bullshit/nextjs-notion-starter-kit#196]
Attached screenshot of the build logs of vercel after I updated the dependencies of notion-client, types, utils and react-notion-x in package.json

Any help would be appreciated!

![image](https://user-images.githubusercontent.com/39328505/144700620-667e915a-ddb1-4eb7-a4ae-5abbefa4182c.png)

**Comment by transitive-bullshit** [comment]
This should be fixed with the latest major release.
