### ISSUE TITLE
How do you prevent the notion URLs from being indexed, and only the Vercel hosted links to make it on the Google?

### ISSUE THREAD

**Issue by thisisnotawill** [transitive-bullshit/nextjs-notion-starter-kit#197]
I'm trying to put up a somewhat anonymous site with the root page living in my personal notion account, but I don't want my personal notion URL to be tied to the post. I've noticed that if you google some of the text in one of Travis's blog posts, the search results show https://transitivebullsh.it/ and not his notion URL. Wondering how he does this! 

Travis, if you see this, just wanted to let you know that this repo is awesome. Thanks so much for putting it up.

**Comment by julbrs** [comment]
Hello,

Maybe that? 

![image](https://user-images.githubusercontent.com/4988590/155252165-a45d27d8-73e1-4b1a-a377-cb9c55006bab.png)

Uncheck Search engine indexing ;)
