### ISSUE TITLE
Can't use search

### ISSUE THREAD

**Issue by yunzhongci** [transitive-bullshit/nextjs-notion-starter-kit#198]
已经解决了

Already resolved

**Comment by ftufkc** [comment]
我遇到了和您相同的问题，您能告诉我您如何解决的吗？我怀疑是因为不支持中文搜索。
I have the same problem as you, can you tell me how you solved it? I suspect it's because Chinese search is not supported.

**Comment by ftufkc** [comment]
> 已经解决了
> 
> Already resolved

我遇到了和您相同的问题，您能告诉我您如何解决的吗？我怀疑是因为不支持中文搜索。
I have the same problem as you, can you tell me how you solved it? I suspect it's because Chinese search is not supported.

**Comment by yunzhongci** [comment]
> > 解决了
> > 解决了
> 
> 我遇到了和你一样，能告诉我你是怎么解决的吗？我怀疑是因为中文搜索不支持。我和你有同样的问题，你能告诉我你是怎么解决的吗？我怀疑这是因为中文搜索不受支持。

config.js的domain 这一项要跟实际使用的域名一致，才能搜索，如果两者不一致就无法搜索

**Comment by transitive-bullshit** [comment]
This has been fixed in the latest release. Thanks
