### ISSUE TITLE
This repo can support 'Table database - Inline' block?

### ISSUE THREAD

**Issue by tsaiggo** [transitive-bullshit/nextjs-notion-starter-kit#199]
Hello, I have a problem.
This repo can support Notion's **_Table database - Inline_** block?
I used **vercel**  to deploy my notion page.But it can not show in the web page.
Sorry, my English is poor.

**Comment by transitive-bullshit** [comment]
There was a bug with some newer inline collection views not rendering properly.

It should be fixed in the latest version.
