### ISSUE TITLE
react-static-tweets need to be fix

### ISSUE THREAD

**Issue by JOduMonT** [transitive-bullshit/nextjs-notion-starter-kit#203]
1. `npm install --force` need to be with  otherwise `npm run dev` will fail but the result is a working website with 21 vulnerabilities (8 moderate, 13 high)
2. `npm audit fix --force` break everything mainly because of `react-static-tweets`

**Comment by transitive-bullshit** [comment]
`react-static-tweets` has been updated and the fix has been incorporated. Thanks!
