### ISSUE TITLE
Need Assist 

### ISSUE THREAD

**Issue by thelapyae** [transitive-bullshit/nextjs-notion-starter-kit#209]
Footer showing copyright 2021, where should I change it?
and how to add Instagram and telegram instead of Twitter and LinkedIn?

May I know how to change the background color from Pinkish to Yellow when viewing from mobile?

Thank You

**Comment by xralphack** [comment]
@thelapyae you can update footer description in components/Footer.tsx
```
 return (
    <footer className={styles.footer}>
      <div className={styles.copyright}>Copyright 2021 {config.author}</div>
 ```
 
 If you want customize styles you should check the css files in the project

**Comment by thelapyae** [comment]
Got it and thank you. I still can't figure out how to change 

iframe wrapper background color in light mode . I've done for dark mode but light mode seem not working.

I use html embedded button in notion and it show ugly square box as background. I tried fix for dark-mode and worked .. bit still not goes well for light mode.

Any idea ? 

You can check what I mean here [https://www.thelapyae.com]()

**Comment by xralphack** [comment]
I have no idea for the "html embedded button". You may need to attach screenshot.

**Comment by thelapyae** [comment]
I can fix it for dark mode ![image](https://user-images.githubusercontent.com/97380388/149945036-f6356808-84e3-46ec-9da3-69e2e045c539.jpeg)

But light mode is still struggling. I already removed background from html code.but still visible. 

![image](https://user-images.githubusercontent.com/97380388/149945171-03c017b4-e671-431c-b117-a7f42dfd2057.jpeg)

You can check out [here](https://www.thelapyae.com)

**Comment by xralphack** [comment]
@thelapyae 

```
.notion-asset-wrapper iframe {  background-color: #fff; }
```

**Comment by transitive-bullshit** [comment]
This has been updated in the the main branch.
