### ISSUE TITLE
Unable to load site locally

### ISSUE THREAD

**Issue by aidanlw17** [transitive-bullshit/nextjs-notion-starter-kit#210]
Hi there,

Thank you for building such a great tool! I'm trying to get a Notion page up and running on it, but after installing dependencies and running `npm run dev` I'm having an issue where my page is never loading. On localhost:3000, the page never finishes loading and no content shows up. I've tried with the default notion page ID as well as my own page ID with no luck, and if I refresh the page then I see NextJS recompiling successfully once again in the logs. After starting the server my log looks like the following:

```
> nextjs-notion-starter-kit@0.1.0 dev /Users/aidan/.../nextjs-notion-starter-kit
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
{
  domain: 'somedomain.com',
  name: 'Aidan Site',
  rootNotionPageId: '78fc5a4b88d74b0e824e29407e9f1ec1',
  rootNotionSpaceId: '',
  description: 'Example site description'
}
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
```

Any help to resolve this would be greatly appreciated! Thanks.

**Comment by jorgeruvalcaba** [comment]
@aidanlw17 make sure your project is updated with the latest changes from the base template and run it with `yarn & yarn dev`

**Comment by transitive-bullshit** [comment]
This should be resolved with the latest release.
