### ISSUE TITLE
How to hide a page?

### ISSUE THREAD

**Issue by NyaMisty** [transitive-bullshit/nextjs-notion-starter-kit#212]
In your example blog, I found that you're having a "Public" property in your database.
And those items that are not public are correspondingly not showing in the blog too.

**Comment by nimble-123** [comment]
did you found any solution for this? i can't find the logic where it filters the displayed blog posts by that `Public` property.

**Comment by NyaMisty** [comment]
Yup I've found it and improved his project by supporting non-shares pages
