### ISSUE TITLE
Table headers sometimes not displaying

### ISSUE THREAD

**Issue by chiperman** [transitive-bullshit/nextjs-notion-starter-kit#214]
## Question 1:
I have some database in my Notion page and put it in my notion-starter-kit page. But the property type of the database can't show in the page. I found that it didn't work well in your [Image Charts](https://transitivebullsh.it/image-charts) too.

Here is the notion page url: https://www.notion.so/dee7103d509d490c963c7159e682e6d5?v=72737ab254dd47cbbb31080615489f30
Screenshots:
![image](https://user-images.githubusercontent.com/34889778/151686496-ff050d4c-b942-4270-b355-731fb1e62436.png)

Hope:
Can we fix it so the page can show the property type correctly?
![image](https://user-images.githubusercontent.com/34889778/151686628-744e78cb-6f27-493b-a148-0eddd1dfdd17.png)

**Comment by transitive-bullshit** [comment]
Hmmm, this seems like a bug in `react-notion-x`, though I'm not sure what's going on.

**Comment by transitive-bullshit** [comment]
If you update to the latest, this should be fixed.
