### ISSUE TITLE
Can zoom the picture when click it?

### ISSUE THREAD

**Issue by chiperman** [transitive-bullshit/nextjs-notion-starter-kit#221]
Can we zoom the photo when we click it? cause some of the picture is so small. If we can zoom it, we can get a better experience
<img width="932" alt="截屏2022-02-15 下午3 40 51" src="https://user-images.githubusercontent.com/34889778/154015027-5d854437-e753-4eeb-8cdc-d11cd9c86e6a.png">

**Comment by transitive-bullshit** [comment]
Support for `medium-zoom` has been fixed and re-added in the latest release 👍
