### ISSUE TITLE
Enable code color during redering 

### ISSUE THREAD

**Issue by NemesisX1** [transitive-bullshit/nextjs-notion-starter-kit#224]
Hello,

I am not able to display my source code with coloured syntax on my website. I tried to use custom CSS to fix it but it works locally and when I deploy it for prod it not longer works.

I tried many times but still got this issue after all.

I made a demo link https://www.juniormedehou.me/test

I use only the basic template with a custom font. Tried to clear everything and just download the raw starter kit but still get the same issue.

**Comment by NemesisX1** [comment]
I will add something

When you go to the page which contains your code, it is working and still displaying syntax colour.

But when I refresh page, it removes colour and display my embedded code only in black

**Comment by transitive-bullshit** [comment]
Proper `Code` block support has been fixed in the latest release. There was a bug with the prismjs integration previously.
