### ISSUE TITLE
Can't show the cover img on the page

### ISSUE THREAD

**Issue by chiperman** [transitive-bullshit/nextjs-notion-starter-kit#228]
When I use the content of the page for the cover IMG, sometimes it can't show the IMG correctly. The HTML class of shows `notion-collection-card-cover-empty`.

<img width="478" alt="截屏2022-03-02 上午9 53 24" src="https://user-images.githubusercontent.com/34889778/156279656-f7a2fe1e-e966-45d5-91dc-d8d116d122fd.png">

**Comment by transitive-bullshit** [comment]
Please follow the issue template and include a notion page ID, so we can reproduce the issue.
