### ISSUE TITLE
Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by angginuraziz** [transitive-bullshit/nextjs-notion-starter-kit#230]
Hi, i found security issue on this lib/map-image-url.ts:24 with code scanning by github, please fix this issue.

![Screenshot 2022-03-12 183911](https://user-images.githubusercontent.com/39976558/158016529-70789b0a-df8c-475d-bc58-678104f8e0ef.png)

Thanks!

**Comment by transitive-bullshit** [comment]
This code doesn't exist in this repo anymore.
