### ISSUE TITLE
Search not working again

### ISSUE THREAD

**Issue by zeyugao** [transitive-bullshit/nextjs-notion-starter-kit#231]
In https://transitivebullsh.it/

![image](https://user-images.githubusercontent.com/6374697/158509863-37499cac-9d58-4e58-9dfc-caef4a9ce441.png)

But indeed there is some results from the api

![image](https://user-images.githubusercontent.com/6374697/158509930-1c5f43e0-aa86-4a65-b1ef-01893d5f5f45.png)

It seems that the frontend doesn't handle the results properly

**Comment by transitive-bullshit** [comment]
I think it's likely that Notion changed something in their private API response format.

Thanks for the report. Will investigate when I find some time.

**Comment by transitive-bullshit** [comment]
This should now be fixed.
