### ISSUE TITLE
Share blog article to social media

### ISSUE THREAD

**Issue by pooriaarab** [transitive-bullshit/nextjs-notion-starter-kit#233]
Hi, 

I've found this great repo 
https://github.com/braydoncoyer/braydoncoyer.dev

Where you can share articles from a notion page to social media. 

Was wondering how we could implement a similar function here?

**Comment by transitive-bullshit** [comment]
This feature request is outside of the scope of the boilerplate. I'm planning on scaling things back quite a bit, so adding more features like this would be moving in the wrong direction for the project.

W.r.t. your question about how to implement the feature on top of this boilerplate, I would recommend asking in a community dedicated to helping with react like on reddit.
