### ISSUE TITLE
Views + Reactions for blog articles

### ISSUE THREAD

**Issue by pooriaarab** [transitive-bullshit/nextjs-notion-starter-kit#234]
Hi, 

This great repo here

https://github.com/braydoncoyer/braydoncoyer.dev

tracks views using plausible.io and reactions using react-share in Supabase, 

how can we implement something similar?

**Comment by transitive-bullshit** [comment]
This feature request is outside of the scope of the boilerplate. I'm planning on scaling things back quite a bit, so adding more features like this would be moving in the wrong direction for the project.

You're more than welcome to fork it and implement it yourself, though 😃
