### ISSUE TITLE
User auth + payment gateway

### ISSUE THREAD

**Issue by pooriaarab** [transitive-bullshit/nextjs-notion-starter-kit#235]
Hi, 

Was wondering how we could implement user auth and payment gateway?

For example, certain pages would require payment to access or user login.

**Comment by transitive-bullshit** [comment]
Closing as this is outside the scope of this boilerplate.

It's meant as a jumping off point; you'd be better off either using a different pre-built solution for these areas or researching how to build them on top of the base this boilerplate provides.
