### ISSUE TITLE
Website 404 space error when page/article title changes

### ISSUE THREAD

**Issue by pooriaarab** [transitive-bullshit/nextjs-notion-starter-kit#237]
Hi, 

I used the default notion template and change the title of one of the articles. 

Once clicking on that article, the website shows the space avatar

![image](https://user-images.githubusercontent.com/42897904/158954318-3f6ca3e5-b928-4a83-b72f-22c9305a750b.png)

All I did was changing "A guide to finding awesome co-founders" to "guide inding". 

Thoughts on how I can fix it?

**Comment by transitive-bullshit** [comment]
This is definitely an annoying bug that's been around for awhile.

My proposal would be to simplify the slug generation to not be auto-generated.

**Comment by transitive-bullshit** [comment]
If this happens, just redeploy your site to vercel.

It's not the best solution, but I think it's good enough for now. Most of the time, the expectation is that your production URLs won't change very often.
