### ISSUE TITLE
How to host outside of Vercel on shared hosting?

### ISSUE THREAD

**Issue by pooriaarab** [transitive-bullshit/nextjs-notion-starter-kit#241]
Hi, 

I wanted to know how we could host our notion website outside of Vercel. with the sync feature (e.g. change in notion, updates in website). 

Any guides would be appreciated. I plan to use Hostinger

**Comment by transitive-bullshit** [comment]
This repo is meant for use with Vercel.

If you want to use another hosting provider, then it won't work out of the box for you.
