### ISSUE TITLE
Some Image loading faild

### ISSUE THREAD

**Issue by allinu** [transitive-bullshit/nextjs-notion-starter-kit#246]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/32992109/160612533-11a70c67-e597-4ab0-9e91-80710ea2399e.png">

**Comment by chiperman** [comment]
@transitive-bullshit Having the same issue and I find out that it works well in Safari but failed in Chromium such as:
1. Chrome (99.0.4844.84)
2. Brave(1.36.122 Chromium: 99.0.4844.88)。

Redeploy or refresh the page、clear the cookies and cache of the browser still can fix the problem.

**Comment by transitive-bullshit** [comment]
@chiperman what OS are you using? I'm having trouble reproducing the issue with the same version of chrome.

**Comment by chiperman** [comment]
Take a screen recording, I found that all the IMG in my blog just can't show. When I fresh the page, it shows shortly and just disappears. Including the avatar in the Head and icon we add in the notion page

View this [site](https://notion.chiperman.tk/%E5%A6%82%E4%BD%95%E7%BB%99%E4%BD%A0%E7%9A%84%E7%BD%91%E7%AB%99%E5%8A%A0%E4%B8%8A-github-contributions-chart-5908e1b1b7114c1f8952cc48c949f949).
![45ev3-fsrqt](https://user-images.githubusercontent.com/34889778/160663409-eebc17a3-ad56-469b-a531-793453bc0507.gif)

<img width="1059" alt="截屏2022-03-30 上午12 46 57" src="https://user-images.githubusercontent.com/34889778/160663715-22c92096-9f56-4ce4-81e4-eb7a38c4c6fa.png">


I can get a log from the chrome console.
```
GET https://notion.chiperman.tk/_next/image?url=https%3A%2F%2Fwww.notion.so%2Fimage%2Fhttps%253A%252F%252Fghchart.rshah.org%252Fchiperman%3Ftable%3Dblock%26id%3D5355f4b9-c825-4eb9-8c94-767b0f5fbd84%26cache%3Dv2&w=1920&q=75 400
```

**Comment by transitive-bullshit** [comment]
@chiperman the images that aren't loading for you are svgs.

This is a next.js setting that disables `next/image` working with svgs by default. To fix it, merge the latest into your code, specifically a9f4bb3

**Comment by transitive-bullshit** [comment]
@allinu I'm pretty sure the issues @chiperman is talking about are separate from what you are seeing.

When you get a chance, can you let me know if you're still seeing the image issues on https://transitivebullsh.it, and if so more info about the browser / OS so I can try to reproduce the issue?

**Comment by chiperman** [comment]
@transitive-bullshit still can't see your avatar and little icon on the header which is the same problem I have.

<img width="1440" alt="截屏2022-03-30 上午9 14 53" src="https://user-images.githubusercontent.com/34889778/160731442-99a2c98c-6842-490b-abed-06269105635b.png">

**Comment by allinu** [comment]
@transitive-bullshit 

OS: Mac OS M1 Monterey 12.3.1 (21E258)
Browser: Chrome 版本 99.0.4844.84（正式版本） (arm64)

Safari display okay 😊 but chrome is not

**Comment by transitive-bullshit** [comment]
Hmmmm, maybe I'm having a hard time understanding or reproducing this issue.

Would one of you guys mind taking a screenshot of the devtools network tab after a refresh (with caching disabled)? Like this one:

![CleanShot 2022-04-04 at 05 49 52@2x](https://user-images.githubusercontent.com/552829/161519493-42ee66a4-bd94-425e-8435-817bc3b33b3b.png)

Also, are there any errors printed to the console?

I want to get more of an understanding of whether it's a format issue, a network issue, or a rendering issue.

Thanks!

**Comment by chiperman** [comment]
@allinu Do you have a chrome-extension named: SimpleRead, I think this extension cause this problem. Can you try to disabled it and refresh the website to see everthing is fine?

**Comment by allinu** [comment]
@chiperman YES!!! You are right!!! But I don't know why, hhha. Thank You

**Comment by allinu** [comment]
Okay, if SimpleRead's problem, I think find the way to solve it. Thanks @chiperman!!

I will close this issue.

Thanks everyone. ❤️
