### ISSUE TITLE
url generate issue

### ISSUE THREAD

**Issue by ZeroOnePro** [transitive-bullshit/nextjs-notion-starter-kit#247]
If the title of the page contains Korean, the Korean part of url will be replaced with a space.

I want to fix this part for SEO optimization. 

I ask for advice on which part to look at.

thanks

**Comment by transitive-bullshit** [comment]
@ZeroOnePro can you include an example Notion page ID I can test?

**Comment by transitive-bullshit** [comment]
Sounds good.

What's the preferred way to include Korean characters in URLs? Could you give me an example of what you'd like one of your URL slugs to look like?

I think the problem is here: https://github.com/NotionX/react-notion-x/blob/master/packages/notion-utils/src/get-canonical-page-id.ts#L33

**Comment by transitive-bullshit** [comment]
Just added a new feature to override the default slug generation functionality.

Now, if you update to the latest version of dependencies (merge latest or run `yarn deps` command) and add a text column `Slug` to your database, that allows you to override the default slug generation. Then just set what you want for the custom slug like in this example: https://transitive-bs.notion.site/Next-js-Notion-Starter-Kit-Template-7875426197cf461698809def95960ebf

Let me know if you still run into issues.

**Comment by ZeroOnePro** [comment]
I can't think of any good ideas except for how to make them in https://domain/한글, just like in English.

I think that can set the slug to English and use the method of making url in English.

thanks a lot have a nice day!
