### ISSUE TITLE
Something wrong with Notion's Gallery view

### ISSUE THREAD

**Issue by ChenZiHong-Gavin** [transitive-bullshit/nextjs-notion-starter-kit#248]
My Notion Page using Gallery seems like this
https://torch-hospital-072.notion.site/Academic-Stuff-076d4f091ae94cb1b0ccc1582f7d3f38
![image](https://user-images.githubusercontent.com/58508660/160746597-4b7ba56a-4c53-4544-b49f-59cf642d70fb.png)
While when I run my app locally or on Vercel, it turns out like
https://my-blog-a2bj2187k-chenzihong-gavin.vercel.app/academic-stuff
![image](https://user-images.githubusercontent.com/58508660/160746687-213b3b8d-c309-4e91-b216-7b24681fac35.png)
The content cannot be shown.
I really like your project and want to help it become a perfect one.
I hope the information above will help.

**Comment by transitive-bullshit** [comment]
This was a bug; notion had added another way to reference collections.

Fixed in latest `react-notion-x`. Update all deps to 6.0.23. Thanks!
