### ISSUE TITLE
react-notion-x: The requested module 'react' does not provide an export named 'useState'

### ISSUE THREAD

**Issue by kgoo124** [transitive-bullshit/nextjs-notion-starter-kit#250]
Getting this error right after cloning the repo, running `npm install` and then `npm run dev`.
It looks like there's an issue in `react-notion-x`. If you could explain what's going on, I could make the fix. Thanks!
![Screen Shot 2022-03-31 at 2 17 16 PM](https://user-images.githubusercontent.com/44537937/161150842-d6b50b55-782c-4f8d-96d9-1bbe7f69623a.png)

**Comment by transitive-bullshit** [comment]
Ahhh, you need to install `node` >= 14.17. I'll update the project to make this more clear.

I recommend using the latest Node v16 or v17 release.

You can easily switch node versions using https://github.com/nvm-sh/nvm
