### ISSUE TITLE
May I use part of root page as home page?

### ISSUE THREAD

**Issue by yangyangisyou** [transitive-bullshit/nextjs-notion-starter-kit#258]
I want to set a part of my page as my home page, because I am not going to share all of page as public, I am not sure how to set it on the site.config, or maybe this feature not support. Does this work? Thanks :)

**Comment by transitive-bullshit** [comment]
This isn't possible out of the box.

I would recommend moving the public parts into their own, isolated notion page and using that page as your root page for your website.
