### ISSUE TITLE
Embedded gif not working

### ISSUE THREAD

**Issue by Vadorequest** [transitive-bullshit/nextjs-notion-starter-kit#264]
Integrating this gif in Notion `https://tenor.com/view/birthday-happy-birthday-balloon-hbd-steve-harvey-gif-22808994` works well on Notion but doesn't display well on the website.

On Notion (iframe element):
![image](https://user-images.githubusercontent.com/3807458/162593732-f7b22f44-1abd-422a-afc5-d717520ef2d6.png)

On website (video element):
![image](https://user-images.githubusercontent.com/3807458/162593739-3b673cbf-d49f-464e-a4a5-1dce54f14131.png)

I can't really share the Notion page because it's writable for everybody, but adding the above URL in any Notion page will be enough to troubleshoot the issue.

I guess the site should use an iframe element, too. (but not sure what that change could break)

**Comment by transitive-bullshit** [comment]
Let's try to keep notion rendering bugs in react-notion-x.

The embedding support can definitely use work. Thanks for the bug report 🙏

**Comment by Vadorequest** [comment]
Ah, sorry. I think as administrator, you might have the ability to move this issue to the right repository.

**Comment by Vadorequest** [comment]
Moved to https://github.com/NotionX/react-notion-x/issues/263
