### ISSUE TITLE
Error - Task timed out after 10 seconds

### ISSUE THREAD

**Issue by Vadorequest** [transitive-bullshit/nextjs-notion-starter-kit#276]
#### Description

My site used to work just fine, but I recently added a bunch of pictures (a lot) and since then the auto-refresh doesn't work anymore.

On the Vercel Functions logs, I get 
`2022-04-23T09:14:28.394Z 5cc63739-5b89-4e3f-8ebb-6d467db86fa0 Task timed out after 10.03 seconds`

I believe it's related to something to do with the images, but I'm not sure where the 10sec limit comes from. Is it Vercel? Can I increase it?

![image](https://user-images.githubusercontent.com/3807458/164888464-182eea86-d36d-420e-9123-f60c639075eb.png)

**Comment by Vadorequest** [comment]
It seems to be coming from the lqip, which is related to generating previews.

Configuring a Redis cache might help, I also found a `10000` ms limit that might be related, not sure:
```ts
export const searchNotion = pMemoize(searchNotionImpl, {
  cacheKey: (args) => args[0]?.query,
  cache: new ExpiryMap(10000)
})
```

**Comment by Vadorequest** [comment]
Ah, I guess increasing that limit will not work unless the Vercel plan is increased from Hobby to Pro.

![image](https://user-images.githubusercontent.com/3807458/164888882-9980a0aa-8475-4261-ba18-895979a96ddf.png)


https://vercel.com/docs/concepts/limits/overview#general-limits

**Comment by Vadorequest** [comment]
Using Redis without changing the timeout did the job.

**Comment by transitive-bullshit** [comment]
For anyone else who ends up here, you have a few options if you're running into Vercel timeouts:

- add redis caching to drastically speed up subsequent page loads
- disable `isPreviewImageSupportEnabled`
- upgrade Vercel to a paid plan

Adding redis is probably the easiest (and cheapest) option.

**Comment by sao-coding** [comment]
@transitive-bullshit 
If Vercel API has a rate limit exceeding 10 seconds, is it useful to configure Redis? Does Redis need to fetch API data before caching?
