### ISSUE TITLE
Chinese title problem

### ISSUE THREAD

**Issue by Coder-itCheng** [transitive-bullshit/nextjs-notion-starter-kit#277]
Hello, there seems to be a problem, when the title of the article is all in Chinese, 404 is displayed when the link is opened, I don't know whether it needs to be configured.

**Comment by transitive-bullshit** [comment]
If anyone else has this problem, the [default template](https://www.notion.so/transitive-bs/Next-js-Notion-Starter-Kit-Template-7875426197cf461698809def95960ebf) has a table with the text property "Slug". If a page has a non-empty Slug property, it will override the default auto-generated URL pathname.
