### ISSUE TITLE
Display properties with names

### ISSUE THREAD

**Issue by jaypozo** [transitive-bullshit/nextjs-notion-starter-kit#280]
I don't think this is built-in, but it would be nice to have an option to display the property name field, on a page that has properties. 

I have this:

https://www.filmcameratimeline.com/pentax-k1000

Note the list of property values, but no names.

![CleanShot 2022-04-25 at 14 05 45](https://user-images.githubusercontent.com/471422/165174960-11714925-c77c-4b54-a3cb-9403cf5a5a9e.png)

I know I could technically use a simple table on the page, but I think it makes sense for the camera data to exist in the page properties for later reuse in other apps and places.

**Comment by transitive-bullshit** [comment]
They're hidden by default. Remove this line of CSS and you should be good: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/styles/notion.css#L174

**Comment by jaypozo** [comment]
Great, I can work with this, thank you!
