### ISSUE TITLE
Latest dark mode changes causing severe white flashing

### ISSUE THREAD

**Issue by raviriley** [transitive-bullshit/nextjs-notion-starter-kit#281]
#### Description

Screen Recording:

https://user-images.githubusercontent.com/8132955/165387569-27dd9980-393d-4af2-9f33-2220ab153a5a.mov

The new dark mode white flashing is horrendous

#### Notion Test Page ID

Go to any site with the new changes, for example https://transitivebullsh.it/ or https://nextjs-notion-starter-kit.transitivebullsh.it/

**Comment by transitive-bullshit** [comment]
Thanks for bringing this to my attention. I'll try to get a fix out in the next day or so.

**Comment by transitive-bullshit** [comment]
This should now be fixed via https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/9afdbe32bfddf898e965cacc49785a29ea78f89a. (update is still deploying to prod, but verified it works on a preview deployment)

There were some things that I liked about [next-themes](https://github.com/pacocoursey/next-themes), and I'm sure it's possible to get it working, but I don't have the capacity to debug it right now.

So I just reverted to using the [old dark mode support](https://github.com/transitive-bullshit/use-dark-mode), which has been tested quite a bit in production.

**Comment by raviriley** [comment]
Thanks for fixing this so quickly!
