### ISSUE TITLE
Not fetching updates from Notion.

### ISSUE THREAD

**Issue by PersistVenture** [transitive-bullshit/nextjs-notion-starter-kit#289]
I deployed on vercel successfully. After deployed the notion page, I did some updats on Notion, but those updates are not shown on deployed website. Should I reployed everytime if make any changes on notion?

Thanks.

**Comment by jaypozo** [comment]
If you have connected the main Notion page with your website, changes should normally appear within a minute or two, without rebuilding. It does for me anyways, deployed on Vercel.

**Comment by PersistVenture** [comment]
@jaypozo can you please share more guidelines to get it.

Thanks.

**Comment by transitive-bullshit** [comment]
Duplicate of #269
