### ISSUE TITLE
Why revert to use-dark-mode?

### ISSUE THREAD

**Issue by fky2015** [transitive-bullshit/nextjs-notion-starter-kit#290]
Hi, I recently noticed there is a [commit](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/9afdbe32bfddf898e965cacc49785a29ea78f89a) that reverts the `next-theme` to `use-dark-mode`.

Just want to ask that is there any reason behind this? It seems that the `next-theme` needs less code.

**Comment by transitive-bullshit** [comment]
See https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/281
