### ISSUE TITLE
top settings？

### ISSUE THREAD

**Issue by Moyi321** [transitive-bullshit/nextjs-notion-starter-kit#291]
How can I have about and Contact, day and night buttons on the left side of the search box at the top like the author?

Thanks!
-->

**Comment by Moyi321** [comment]
https://gitee.com/Lloveyou/picture_bed/raw/master/img/325432532.png

**Comment by transitive-bullshit** [comment]
Change your site config to use this: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/site.config.ts#L51-L61

**Comment by aghosh0605** [comment]
But how do implement day and night buttons?

**Comment by Moyi321** [comment]
//navigationStyle: 'default'
   navigationStyle: 'custom',
   navigationLinks: [
     {
       title: 'Picture',
       pageId: '33e8d04e067143a989323ca9af69b3c7'
     },
     {
     title: 'Air-cloud',
       pageId: '100b875f1e2e4d85b57d2798e4191668'
    }
    ]
} )

**Comment by aghosh0605** [comment]
Yeah, I got it. But there should be an option where I can implement the day and night button without any custom pages like about contact etc. Thanks for all your effort, I can't believe that I got the message within 5 min. Loved it.

**Comment by aghosh0605** [comment]
navigationStyle: 'custom',
  navigationLinks: [
    // {
    //   title: 'About',
    //   pageId: 'f1199d37579b41cbabfc0b5174f4256a'
    // },
    // {
    //   title: 'Contact',
    //   pageId: '6a29ebcb935a4f0689fe661ab5f3b8d1'
    // }
  ]

**Comment by aghosh0605** [comment]
Solution I found
You can close this issue. This is solved overall.

**Comment by aghosh0605** [comment]
Thank you @Moyi321

**Comment by Moyi321** [comment]
> 

you are welcome
