### ISSUE TITLE
Code block does not respond in the case of small devices

### ISSUE THREAD

**Issue by ChiaYuSu** [transitive-bullshit/nextjs-notion-starter-kit#294]
#### Description

I found that the Code block does not respond when I test using a small device, I don't know what the problem is.
But I see that your official website (https://transitivebullsh.it/oss-twitter-algorithm-part-1) is working fine.
![image](https://user-images.githubusercontent.com/26423040/166401313-66c5c83f-aed5-49d5-8686-701458219c30.png)

#### Notion Test Page ID
https://jacksu.tw/toc

**Comment by ChiaYuSu** [comment]
I have fixed by myself already. Add `width: 100%` in `.notion-list` at `styles/notion.css` file

**Comment by ChiaYuSu** [comment]
I have fixed by myself already. Add `width: 100%` in `.notion-list` at `styles/notion.css` file

**Comment by transitive-bullshit** [comment]
Ahh I think this may be a `code` block inside of a list? Seems like an edge case that we probably weren't handling properly.

**Comment by ChiaYuSu** [comment]
> Ahh I think this may be a `code` block inside of a list? Seems like an edge case that we probably weren't handling properly.

Yes, you are right.
I have fixed by myself already. Add `width: 100%` in `.notion-list` at `styles/notion.css` file
