### ISSUE TITLE
RSS feed not generated for nested items

### ISSUE THREAD

**Issue by y1zhou** [transitive-bullshit/nextjs-notion-starter-kit#303]
#### Description

The https://example.com/feed page contains items of the index page and the blog posts, but nested pages/notion databases are not showing up in the feed. For example, posts in `/series` of my Notion page attached below are not in the generated feed.

Thanks for the wonderful work! Please let me know if additional details are needed.

#### Notion Test Page ID

`a6647240285246eb9500bcd751c11b18`

**Comment by transitive-bullshit** [comment]
This will take some tweaking of the logic here https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/pages/feed.tsx#L50 where we're filtering out pages which aren't part of the "main database".

This is really subjective logic, and you probably want to just remove a few of the conditions to include more pages.

Hope that helps 🙂

**Comment by y1zhou** [comment]
@transitive-bullshit Makes total sense! Thanks for pointing to the specific line of the logic.
