### ISSUE TITLE
How to include a custom HTML element in the banner position?

### ISSUE THREAD

**Issue by thanhsonng** [transitive-bullshit/nextjs-notion-starter-kit#324]
#### Description

Hi @transitive-bullshit. I'm building my blog and your template has been super helpful to get me started. Thank you for this wonderful work 🎉 

This is not an issue but rather a small question (If this is not an appropriate way to ask please let me know). I want to achieve something similar to [your About page](https://transitivebullsh.it/about), where you have an interactive canvas in the place where the post banner usually is. I did some search about custom HTML in Notion but found nothing useful. 

<img width="1373" alt="Screen Shot 2022-06-11 at 18 28 40" src="https://user-images.githubusercontent.com/28614996/173185989-566ec558-e51f-455a-8bf1-414ea03c6690.png">

Can you share how you achieved it? I can think of only one way, which is to write custom JSX for that whole page, but then I need to ensure the HTML structure of a normal Notion page with all the correct classes. 

#### Notion Test Page ID

N/A

**Comment by si1k** [comment]
I was intrigued by it as well. Travis did it in the Next.js code (not in Notion). The feature is in the `transitive-bullshit` branch. 

Travis detects if the page is the `About` page and if so, adds a component. Hope this helps. 

Here is a link to the code.

https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/2bf2ff927cc5bb01d5ee8176f56a91fbae317969/components/NotionPage.tsx#L232

**Comment by thanhsonng** [comment]
Thank you very much @si1k it helped! I thought this repo is for the template only so I didn't expect Travis's code in any branch at all! 🥲 Issue closed
