### ISSUE TITLE
Command "yarn run build" exited with 1

### ISSUE THREAD

**Issue by PersistVenture** [transitive-bullshit/nextjs-notion-starter-kit#346]
Everything works perfect till 

npm run dev

but when I run the command - npm run deploy

after everything giving below message:

Command "yarn run build" exited with 1

is there any help to resolve this issues? 

Reg.

**Comment by PersistVenture** [comment]
yes. I have.

**Comment by transitive-bullshit** [comment]
Can you paste the output of `yarn run build`?

**Comment by PersistVenture** [comment]
Build error occurred
--
10:48:50.822 | Error: Collecting page data for /[pageId] is still timing out after 2 attempts. See more info here https://nextjs.org/docs/messages/page-data-collection-timeout
10:48:50.822 | at onRestart (/vercel/path0/node_modules/next/dist/build/index.js:489:31)
10:48:50.822 | at Worker.isPageStatic (/vercel/path0/node_modules/next/dist/lib/worker.js:49:40)
10:48:50.822 | at runMicrotasks (<anonymous>)
10:48:50.822 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
10:48:50.822 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:48:50.822 | at async /vercel/path0/node_modules/next/dist/build/index.js:555:48
10:48:50.822 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:48:50.822 | at async Promise.all (index 1)
10:48:50.822 | at async /vercel/path0/node_modules/next/dist/build/index.js:536:13
10:48:50.823 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
10:48:50.863 | error Command failed with exit code 1.
10:48:50.863 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:48:50.944 | Error: Command "yarn run build" exited with 1

**Comment by mhjohnso-purdue** [comment]
I am having the same issue

**Comment by LauraMQuiros** [comment]
i am having the same issue

**Comment by PolyRocketMatt** [comment]
For other people having this issue, what solved it for me is going to the settings page on Vercel itself and overriding the install command (by default I suppose it uses `yarn install`) with `npm install`. 

Normally, this will let the building process of Vercel execute `npm install` instead of `yarn install`. If `npm install` succeeded on your system, I don't see any reason why it would now fail on VerceL.
