### ISSUE TITLE
How can I delete the github button in the upper right corner?

### ISSUE THREAD

**Issue by ghost** [transitive-bullshit/nextjs-notion-starter-kit#347]
as the title says
this is a great project
But I think the logo of github in the upper right corner affects the appearance..
![image](https://user-images.githubusercontent.com/106905547/180258631-64fd1e34-ba29-401a-8c77-cd9d769b1002.png)

**Comment by vuanvin** [comment]
You could modify the file "components/GitHubShareButton.tsx".

**Comment by rescuevessel** [comment]
hey - you just need to delete or comment out this line in NotionPageTSX: <GitHubShareButton />

**Comment by vasfvitor** [comment]
Here what I've done:
1.Removed the lines `<GitHubShareButton />`  and `import { GitHubShareButton }` from  `components/NotionPage.tsx`
2.Deleted the file `GitHubShareButton.tsx` at `/components`
3.And removed the whole CSS at `components/styles.module.css`

```
@media (max-width: 1360px) {
  .githubCorner {
    display: none;
  }
}

.githubCorner:hover .octoArm {
  animation: octocat-wave 560ms ease-in-out;
}

@keyframes octocat-wave {
  0%,
  100% {
    transform: rotate(0);
  }
  20%,
  60% {
    transform: rotate(-25deg);
  }
  40%,
  80% {
    transform: rotate(10deg);
  }
}

@media (max-width: 500px) {
  .githubCorner:hover .octoArm {
    animation: none;
  }

  .githubCorner .octoArm {
    animation: octocat-wave 560ms ease-in-out;
  }
}


```

I may have missed something but at least visually it won't show the GitHub logo.
