### ISSUE TITLE
api/social-image Serverless Function error

### ISSUE THREAD

**Issue by itsbrex** [transitive-bullshit/nextjs-notion-starter-kit#348]
#### Description

![image](https://user-images.githubusercontent.com/9772694/180296404-9716ab45-15dd-4d26-9e2a-7f9fdefaeb39.png)

#### Notion Test Page ID

This is the rootPageId: 22b650d3913540ddade133474cf9fc88

Build fails on Vercel. I've tried reducing the image quality setting, but whatever I try I always get `"api/social-image" is 50.23mb` in Vercel

🤔

**Comment by transitive-bullshit** [comment]
I've removed the headless chrome OG approach in favor of [Vercel's new edge-based OG image generation](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation), which is quite a bit faster, simpler, and best of all doesn't include any additional dependencies. https://github.com/transitive-bullshit/nextjs-notion-starter-kit/pull/383
