### ISSUE TITLE
Change dark-mode bg-color

### ISSUE THREAD

**Issue by RickyWanga** [transitive-bullshit/nextjs-notion-starter-kit#351]
So, I tried looking for the styling of .dark-mode and i can't seem to locate where can I change the color for the dark-mode from the gray to a more darker color, all I seem to get is the compiled css, but even adding a global style for .dark-mode in notion.css doesn't seem to make any changes.

**Comment by transitive-bullshit** [comment]
It's in https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/styles.css#L80

You can override this by adding something like this to your global CSS:

```css
.dark-mode {
  --bg-color: red;
}
```

You may need to add additional CSS specifiers to make this definition override the one in `react-notion-x`. You'll need to test it out and see which one is taking precedence in your browser's CSS inspector to tell for sure.

Hope that helps.

**Comment by RickyWanga** [comment]
Ok thanks, how can I default the site to load in light-mode instead of dark-mode right now?
