### ISSUE TITLE
Possible to use Notion-API-Worker instead of Notion API?

### ISSUE THREAD

**Issue by designedbyclu** [transitive-bullshit/nextjs-notion-starter-kit#354]
#### Description
First of all thanks for building this starter kit for an easier quick setup. However in China mainland fetching Notion API server might too slow due to the firewall, might need set a Proxies for quick access. I tried built a website with deploy personal [Notion-API-Worker](https://github.com/splitbee/notion-api-worker)  , which can solve the fetch time issue. Not sure if this is possible there is an option to point to my private worker instead of the current API?

Thanks!

**Comment by minesunny** [comment]
中国用户额外配置cloudflare即可

**Comment by transitive-bullshit** [comment]
This boilerplate is designed for Vercel and `react-notion-x`. `notion-api-worker` uses a completely different API abstraction from `notion-client` and is not compatible with this project.
