### ISSUE TITLE
Alternative to next-api-og-image for social image generation

### ISSUE THREAD

**Issue by FranciscoMoretti** [transitive-bullshit/nextjs-notion-starter-kit#360]
### Description
The dependency of `next-api-og-image` and subsequently, of `chrome-aws-lambda` can be a bit problematic. My Vercel builds were reporting that the compressed serverless function was a bit over the limit (`50.1mb > 50mb limit`).

**I wonder if there is a plan to replace it with something else.**

### Cloudinary alternative
I've implemented **automatic image generation with https://cloudinary.com/**. I've combined this repository with the method from this post https://delba.dev/blog/next-blog-generate-og-image. 
There is a **free plan** that could be useful for most people. However, I understand that **it's not ideal** because it requires some configuration (creating an account, uploading an image, etc).

#### Example
- In [this repository](https://github.com/FranciscoMoretti/franciscomoretti.com/blob/3171b10b094c92ec04f098e06d730e255da6c190/pages/api/social-image.tsx) you can see the modifications to the `social-image` API.
- Working API generates social-images like this one: https://www.franciscomoretti.com/api/social-image?id=b0405f73-026a-46a3-84ae-170c5918f8e7

### Actions
I can create a PR to include Cloudinary as a replacement or an alternative. I'm not sure if that's desired though.
There might be a better option that directly replaces `chrome-aws-lambda`. I'd be happy to work on that replacement if it exists. 

P.S.: Thanks for this awesome repo!

**Comment by soumendrak** [comment]
@FranciscoMoretti 
Your PR will definitely help me (and many others). If you can create it will be super helpful. Thank you.

**Comment by transitive-bullshit** [comment]
I ended up switching things over to [Vercel's new edge-based OG image generation](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation), which is quite a bit faster, simpler, and best of all doesn't include any additional dependencies. https://github.com/transitive-bullshit/nextjs-notion-starter-kit/pull/383

**Comment by transitive-bullshit** [comment]
Feel free to re-open if you'd like to discuss other alternatives, though I think it's clear this is the direction that Next.js is headed in.
