### ISSUE TITLE
Notion board view cannot be displayed

### ISSUE THREAD

**Issue by linafaik08** [transitive-bullshit/nextjs-notion-starter-kit#369]
Thank you for this great project!

Unfortunately, I have not been able to use it because the pages with an [board view](https://www.notion.so/help/guides/board-view-databases) do not display.

Here is a screenshot of the results.
<img width="1157" alt="Capture d’écran 2022-08-30 à 12 03 00" src="https://user-images.githubusercontent.com/33423426/187409428-ab752171-2b41-4488-9d08-e3577ebccc26.png">

Please keep me informed if this changes in the future.

Thanks!

**Comment by transitive-bullshit** [comment]
This may be fixed with the latest changes in `react-notion-x`. Try pulling in the latest changes from the `main` branch to see if your problem is fixed.

**Comment by transitive-bullshit** [comment]
If you're still having issues with database views, please open an issue on the underlying notion renderer https://github.com/NotionX/react-notion-x
