### ISSUE TITLE
How do I use equation blocks?

### ISSUE THREAD

**Issue by yanyanlongxia** [transitive-bullshit/nextjs-notion-starter-kit#37]
Can you add support for equations?

Like [this page](https://notion.yylx.tech/test). It should look like [this](https://www.notion.so/yylx/test-f22113f0cbf44f9cbf54a76d073665a7) , but there is nothing. This looks like a mistake in the equation.

**Comment by transitive-bullshit** [comment]
Hey @yanyanlongxia, equations are supported but you need to opt into using them.

See my answer here: https://github.com/NotionX/react-notion-x/issues/20

Let me know if you think this should be enabled by default and if you run into any issues getting it to work.

**Comment by yanyanlongxia** [comment]
Thank you very much, [it works!](https://nextjs-notion-starter-kit-1o1k37nv8.vercel.app/test).  I think this should be enabled by default because equation is an important element of Notion, especially for students.

By the way, does this project support sitemap?

**Comment by transitive-bullshit** [comment]
Awesome -- I'll look into adding equation support by default. The key is to keep it lazy loaded so it doesn't add anything to pages which don't use equations.

Sitemaps aren't supported yet (you can add a manual one to `public/sitemap.xml`), but I'll be adding sitemap soon in https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/39

**Comment by transitive-bullshit** [comment]
I just updated the default to have equations enabled by default (but loaded via `next/dynamic`).

I still think you should opt into adding the Katex CSS since that's harder to lazy load. What do you think?

**Comment by yanyanlongxia** [comment]
Yes, lazy load is also necessary since we often use a lot of equations.
