### ISSUE TITLE
Logo pretends to be transparent

### ISSUE THREAD

**Issue by JOduMonT** [transitive-bullshit/nextjs-notion-starter-kit#382]
#### Description
I tried with an SVG and a PNG, but both appear with a bottom whiter than the shadow made by the top banner.

#### see 
https://jdmnt.notion.site/Jonathan-Dumont-c8776ac02fba4a26b55ef1955471938c vs https://jodumont.com

**Comment by transitive-bullshit** [comment]
Remove these lines and it should work for you https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/styles/notion.css#L346-L349
