### ISSUE TITLE
can 't toggle dark or light mode

### ISSUE THREAD

**Issue by loda13** [transitive-bullshit/nextjs-notion-starter-kit#396]
aflter clicked the toggle button, it stucked and have no response after clicking, 
![image](https://user-images.githubusercontent.com/10447318/200182079-47e8e31c-51d0-4d15-b908-83e040c22ca0.png)

the reverse is the same
can only be restored after reopening a new page
can visit lodatang.com to verify the problem

**Comment by 1oda** [comment]
![image](https://user-images.githubusercontent.com/10447318/200182329-ddcae547-6e1b-4975-9f20-8d24e87109bc.png)

**Comment by transitive-bullshit** [comment]
There seems to be other problems with your site; it hangs when I try to close the tab. Do you have the repo with a list of commits / changes you've made to the base repo?

I think the problem likely has nothing to do with toggling dark mode and is related to some other change.

**Comment by loda13** [comment]
![image](https://user-images.githubusercontent.com/10447318/200318816-21e33db2-c0e8-4f1a-b3dc-6d10c7441317.png)
![image](https://user-images.githubusercontent.com/10447318/200318872-399f271c-41ac-488c-8643-2454fc73cb49.png)

only some basic configuration information and icons have been modified

**Comment by loda13** [comment]
remove this stuff  ， it works

![image](https://user-images.githubusercontent.com/10447318/201476069-9c3d87f1-7980-45fe-866e-2149cc467f09.png)
