### ISSUE TITLE
PDF only shows the first page

### ISSUE THREAD

**Issue by yanyanlongxia** [transitive-bullshit/nextjs-notion-starter-kit#40]
I wanted to enable PDF by adding `import { NotionRenderer, Equation, Pdf, Code, Collection, CollectionRow } from 'react-notion-x'` and  `pdf: Pdf,`. It seems that [it](https://notion.yylx.tech/test) works. But it only shows the first page while the PDF has 31 pages! What's wrong with it?

**Comment by yanyanlongxia** [comment]
[the original notion page](https://www.notion.so/yylx/test-f22113f0cbf44f9cbf54a76d073665a7)

**Comment by transitive-bullshit** [comment]
Hey @yanyanlongxia, thanks for the bug report.

I just fixed this in `react-notion-x`. You can use `34d650c65da34f888335dbd3ddd141dc` as a test page or use your own test page.

Just upgrade `react-notion-x` and you should be all set.

**Comment by yanyanlongxia** [comment]
Thank you, it works now.
