### ISSUE TITLE
3 kinds of Page Load Error during building

### ISSUE THREAD

**Issue by sivannavis** [transitive-bullshit/nextjs-notion-starter-kit#406]
#### Description

Hi, thanks for this super useful design!
After developing locally without any problem, I run into 3 types of errors that my building failed:

```
page load error {
  pageId: 'a6687d04-b12d-4157-97b4-cfb247e76bff',
  spaceId: 'b74133af-844e-4972-b144-c12554ed8914'
} undefined Response code 502 (Bad Gateway)


page load error {
  pageId: 'a0dd80d0-0d2f-411c-9c0d-5e67da2ae9b3',
  spaceId: 'b74133af-844e-4972-b144-c12554ed8914'
} undefined Notion page not found "a0dd80d00d2f411c9c0d5e67da2ae9b3"


# duplicate page
error duplicate canonical page id {
  canonicalPageId: 'ml',
  pageId: 'bb6c683a-568e-435c-a588-89a45ae93849',
  existingPageId: '43a0d6d4-3065-4358-9133-b41f231f62b0'
}
```
I think the "undefined Notion page not found" comes when there's an empty page in a database with only title and properties. And when I go to these pages such as http://localhost:3000/e9014714-c38c-4dda-8b6a-7b011fb77d87 I saw:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/50509896/202922133-94d9cde4-3cd4-4db1-b09f-f754f1185fc2.png">

And the last duplicate error I have resolved by deleting them... But can't solve others and can't find which page it is through the id.

#### Notion Test Page ID

My rootNotionPageId: '9fb4d37f1fe44c6d85e88bc5c521eb4f'

**Comment by sivannavis** [comment]
Is it possible just to throw a 404 error for these pages after building?

**Comment by piavgh** [comment]
Hi @sivannavis , did you solve this issue?

**Comment by sivannavis** [comment]
@piavgh kind of. Since there are too many links and linked databases on my page, I just closed access to some of them to make it work.

**Comment by marharyta** [comment]
@piavgh @sivannavis @transitive-bullshit any other alternatives? I cannot unfortunately do it an dI need to figure out a way to deploy my project :)

**Comment by woensug-choi** [comment]
use `includeNotionIdInUrls: true` in the `site.config.ts` to bypass the issue.

**Comment by juliaramosguedes** [comment]
I was also with this issues and I fixed it adding the `rootNotionSpaceId` property in the `site.config.ts`
I tried to use `includeNotionIdInUrls: true` but it only worked for duplicate canonical page id errors
