### ISSUE TITLE
Jump to blocks in the same page through navigationLinks

### ISSUE THREAD

**Issue by sivannavis** [transitive-bullshit/nextjs-notion-starter-kit#407]
#### Description

Hi, I hope to use the navigation link to jump to the blocks in my root page, but it won't work, I used the link to each block like this
```
navigationStyle: 'custom',
  navigationLinks: [
    {
      title: 'About',
      pageId: ''
    },
    {
      title: 'Contact',
      pageId: ''
    }
```

**Comment by sivannavis** [comment]
I also wanna ask if there's a way to add the table of contents on right side as other pages on the root page?

**Comment by HaiyanKong** [comment]
May be you can refer this website https://1c1-2tpm50jki-1chang1.vercel.app/#link-careers, the blogger achieved the effect you described. The corresponding change code here https://github.com/1chang1/1c1-dev/commit/52918472d5da636ef84c1105ac057600623c7260

**Comment by sivannavis** [comment]
Thank you!
