### ISSUE TITLE
Embedded video support

### ISSUE THREAD

**Issue by yanyanlongxia** [transitive-bullshit/nextjs-notion-starter-kit#41]
There should be an embedded video at the bottom of the [page](https://yylx.tech/copy-of-test#ab59ba27844348a2887ea02965f2aea5), but there is nothing.

[The original notion page](https://www.notion.so/yylx/Copy-of-test-bc6deda4f479457ab3e2435ae9e585ff)

**Comment by transitive-bullshit** [comment]
This should be fixed now if you update to latest `react-notion-x`.

We weren't handling embedded videos aside from external YouTube videos.

**Comment by transitive-bullshit** [comment]
See this page for a live example https://react-notion-x-demo.transitivebullsh.it/file-uploads-34d650c65da34f888335dbd3ddd141dc

**Comment by yanyanlongxia** [comment]
Thanks. It works

**Comment by jorgeruvalcaba** [comment]
@transitive-bullshit Found another issue with an embedded video: https://jorgeruvalcaba.dev/add-tab-to-search-in-your-gatsby-blog-e6082ecef65d4f82a333b9f62335a51a. Seems that the styles are not being applied as expected.
