### ISSUE TITLE
Unstable display of database gallery view on root page

### ISSUE THREAD

**Issue by sivannavis** [transitive-bullshit/nextjs-notion-starter-kit#413]
#### Description

Hi! I discovered lately that sometimes the gallery view of the database disappears on my root page, and that database became only a link. But after a while of refreshing and waiting, it's there again.

#### Notion Test Page ID
rootNotionPageId: '9fb4d37f1fe44c6d85e88bc5c521eb4f'

**Comment by mhjohnso-purdue** [comment]
I have been running into the same issue. @sivannavis were you able to fix it?
