### ISSUE TITLE
Code syntax highlight isn't working for python?

### ISSUE THREAD

**Issue by Mvbbb** [transitive-bullshit/nextjs-notion-starter-kit#43]
This is code look like in notion doc
![image](https://user-images.githubusercontent.com/56795364/107000394-c6b50300-67c2-11eb-95f8-6c06de41e187.png)
but in my site the code highlight don't work
![image](https://user-images.githubusercontent.com/56795364/107000506-f49a4780-67c2-11eb-963a-d411a8995685.png)
Then i use another device to visit my site, highlight still don't work.

This situation happend from time to time, sometime the code highlight works well, but sometime it don't work.

root notion doc: https://www.notion.so/Python-c21c13483cfb4fd48adae93b0f76e677
my site: https://www.yzh.im/python#ed33fd17d0954b6082242a0a0913649e

**Comment by yanyanlongxia** [comment]
This is because Python is not supported by default.
 Add ``import 'prismjs/components/prism-python' `` in ``_app.tsx`` will be ok.

这是因为默认不支持Python
在``_app.tsx``中加入 ``import 'prismjs/components/prism-python' ``就行了

**Comment by transitive-bullshit** [comment]
Happy to add some more languages by default. What do you think?

**Comment by yanyanlongxia** [comment]
I added Python, clike, c and cpp

**Comment by Mvbbb** [comment]
> This is because Python is not supported by default.
> Add `import 'prismjs/components/prism-python' ` in `_app.tsx` will be ok.
> 
> 这是因为默认不支持Python
> 在`_app.tsx`中加入 `import 'prismjs/components/prism-python' `就行了

thanks,谢谢

**Comment by transitive-bullshit** [comment]
@yanyanlongxia should these be included in the defaults?

**Comment by yanyanlongxia** [comment]
I think they are necessary, Because these languages are popular.

**Comment by transitive-bullshit** [comment]
This should be fixed in the latest release.

We're now importing a lot more prism languages by default: https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/third-party/code.tsx
