### ISSUE TITLE
Social Image API fails to Generate

### ISSUE THREAD

**Issue by pijush41** [transitive-bullshit/nextjs-notion-starter-kit#435]
Description
Even after the implementation of https://github.com/transitive-bullshit/nextjs-notion-starter-kit/pull/383 social images are not coming as expected. Only a blank white background webpage is coming if you click on the below-mentioned social-image URL.

Notion Test Page ID
Web site: https://yogchitralaya.com/
Page ID: 0b1d7e63b2dd42e490ddabbcc61d798a
Github Repo:  https://github.com/pijush41/yogchitralaya

Social Image URL
https://yogchitralaya.com/api/social-image?id=0b1d7e63b2dd42e490ddabbcc61d798a

**Comment by transitive-bullshit** [comment]
Hmmm, seems to be a bug with `@vercel/og` or satori or possibly a bug getting the page's JSON data in that serverless handler.

1. Can you see if there are any errors in the Vercel logs when generating a new social image?
2. Are social images working for you locally w/ the dev server?

**Comment by skybird-dev** [comment]
@transitive-bullshit Travis, I've included the errors I get in Vercel for Social Image sharing:

```
/api/social-image?id=a0dc2cd9-e2e2-43c3-b24c-2e9d68e45845
10:26:50:98
ID:
lbr5k-1673461608830-6a24bc1a56d8
Error: Can't load image https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F38c8af74-b174-4df5-b9c8-91561fe24ac8%2F210.jpeg?table=block&id=a0dc2cd9-e2e2-43c3-b24c-2e9d68e45845&cache=v2: Unsupported image type: unknown
    at node_modules/satori/dist/index.wasm.js:5:2790
/api/social-image?id=a0dc2cd9-e2e2-43c3-b24c-2e9d68e45845
10:26:50:98
ID:
lbr5k-1673461608830-6a24bc1a56d8
Error: Can't load image https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F38c8af74-b174-4df5-b9c8-91561fe24ac8%2F210.jpeg?table=block&id=a0dc2cd9-e2e2-43c3-b24c-2e9d68e45845&cache=v2: Unsupported image type: unknown
    at worker.js:18:2815
    at worker.js:56:11409
```
![Screen Shot 2023-01-11 at 10 28 25 AM](https://user-images.githubusercontent.com/117532029/211892783-408ebd33-1655-4fc4-8214-32c2f3fae8f6.png)

In the past, social image sharing worked perfectly regardless of image origin (i.e., user-uploaded cover images via Notion or Unsplash.com). But it stopped working at some point, and I'm still troubleshooting.

Currently, I have two different builds: one uses KY, and the other does not.

With KY, Unspash.com cover images render in iMessage and Facebook-based sharing (i.e. WhatsApp), whereas the one without KY renders Unsplash.com images only in iMessage. Neither method will render an image that I upload to Notion.
I won't show without KY, as it would be redundant. Note that the same errors are given (but if you need further confirmation, please ask).

The article I just wrote for testing purposes is available at https://www.skybird.science/social-media-microbiome 
It does not render the user-uploaded cover image on WhatsApp (Facebook based):
![Screen Shot 2023-01-11 at 10 36 48 AM](https://user-images.githubusercontent.com/117532029/211893175-f5eb5e91-afe7-44f7-bdcc-a008152995df.png)

Nor iMessage:
![Screen Shot 2023-01-11 at 10 36 28 AM](https://user-images.githubusercontent.com/117532029/211893207-c1f16097-e363-4cac-a513-d49457b56e71.png)

With Unsplash.com covers versus without:
![Screen Shot 2023-01-11 at 10 17 27 AM](https://user-images.githubusercontent.com/117532029/211892616-2d9c1575-c58c-47d4-98f5-07bac6f2ef90.png)
![Screen Shot 2023-01-11 at 10 16 21 AM](https://user-images.githubusercontent.com/117532029/211892628-81e4af22-ab0d-40e1-ad40-242f17f9f258.png)

The URLs for the articles:
https://www.skybird.science/motor-neuron-disease
https://www.skybird.science/diabetes

If you have some insights, Travis, we would appreciate it.

**Comment by thanhsonng** [comment]
I also get this error. 

1. The error log only shows up occasionally on Vercel even when I repeatedly visit the social-image API and always get a blank page.
2. Social images are working fine locally. I use Node 18, and the Node runtime of my Vercel app is configured to Node 18 as well.

**Comment by abhidadhaniya23** [comment]
Hi everyone, 

I found a solution for `unauthorized` response which are getting in production while hitting the social image endpoint. I've mentioned [here](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998).

**Comment by ChiaYuSu** [comment]
@abhidadhaniya23 
It's work, thank you.

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

Examples:

- [nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44](https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44)
- [transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396](https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396)

**Comment by transitive-bullshit** [comment]
https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998 is also required on Vercel's side for the project to be public in order for social auth to work.
