### ISSUE TITLE
Add support for pages without header

### ISSUE THREAD

**Issue by tiulpin** [transitive-bullshit/nextjs-notion-starter-kit#44]
Hello, great repo, thank you for the work 🙏

Are you planning to add support for pages that do not include a header?
As you can see on the screenshot there is an empty space and the part of the title is hidden by the avatar:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/13538286/107123858-225dba00-68b1-11eb-90fc-82c44a6903eb.png">

**Comment by transitive-bullshit** [comment]
Ahh yep that looks like a bug that was recently introduced.

Let me look into fixing it now..

**Comment by transitive-bullshit** [comment]
@tiulpin can you send me the ID of the notion page you're testing with?

**Comment by tiulpin** [comment]
Yes, sure, it's `Data-Scientist-11ffd65d6e53498ea174f6343857f643`

**Comment by transitive-bullshit** [comment]
Hey @tiulpin, this should be fixed now if you update to latest `react-notion-x`.

btw, the reason I ask for the ID up front is to make efficient use of my time as I'm responding to a bunch of issues like this.

Thanks!
