### ISSUE TITLE
Katex equations left indented

### ISSUE THREAD

**Issue by shenoynikhil** [transitive-bullshit/nextjs-notion-starter-kit#442]
#### Description

I have math blocks in my pages and while rendering they are all left indented. How could I have the centre alignment that is present as default?
- The indentation is right when I just do share on web and check it through my browser [Link](https://shenoynikhil.notion.site/Different-Ways-to-Interpret-Derive-The-Variational-Lower-Bound-ELBO-673cf34c454242d9afb740955a10f82a)
- On using vercel and this repo, it becomes left indentation. [Link](https://shenoynikhil.vercel.app/different-ways-to-interpretderive-the-variational-lower-bound-elbo)

**Comment by zhouxingyu-warwick** [comment]
Meet the same questions on my notion website.

**Comment by omarcostahamido** [comment]
@shenoynikhil @ghost same here.
The problem runs deeper in react notion x
But I found a solution and proposed as a PR #545
