### ISSUE TITLE
Remove pages in sitemap which are not published ?

### ISSUE THREAD

**Issue by slamer59** [transitive-bullshit/nextjs-notion-starter-kit#443]
#### Description
Unpublished sitemap seemed to be added to sitemap.xml

Do you have an idea on where to filter this ?

**Comment by transitive-bullshit** [comment]
This should be a pretty small change to the code to filter unpublished pages. Sorry I don't have time to fix this right now.

**Comment by slamer59** [comment]
Hello,
i am still trying to find a small change to filter by specific database property (let's say **public** filter == true)

I am able to filter pages thanks to [notionhq](https://developers.notion.com/reference/post-database-query)
```



const { Client } = require('@notionhq/client');

const notion = new Client({ auth: process.env.NOTION_API_KEY });

(async () => {
  const databaseId = "somedbID";
  const response = await notion.databases.query({
    database_id: databaseId,
    filter: {
      or: [
        {
          property: 'Public',
          checkbox: {
            equals: true,
          },
        },
      ],
    },
  });
  console.log(response);
})();

```

I am not able to see if I can filter [here](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/7092e4d3d24916ec40693f66afddce0497918c92/lib/get-site-map.ts#L37) 

If you can point me to where the query is made, maybe I will propose a solution without notionhq.
