### ISSUE TITLE
Nested Elements Inside To-do List Elements Do Not Render

### ISSUE THREAD

**Issue by pavlovcik** [transitive-bullshit/nextjs-notion-starter-kit#45]
I checked the HTML and looks like the child elements do not make it through rendering.

**Original Notion Page**
https://www.notion.so/delete-me-after-bug-report-b426fc66d3c347d0b1628ef1564ef7b0

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/107141108-44c0f900-68ec-11eb-9410-65e80243fbdd.png">

**Rendered Page**
https://dao.ubq.fi/delete-me-after-bug-report

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/107141100-383ca080-68ec-11eb-8d33-5640d08e8ab7.png">

**Comment by transitive-bullshit** [comment]
Thanks, Alex.

This should be fixed now. 💪
