### ISSUE TITLE
Map URLs with a custom config: is it possible?

### ISSUE THREAD

**Issue by tiulpin** [transitive-bullshit/nextjs-notion-starter-kit#46]
Hi, thanks again for the fast fixes, it's really cool 🚀 And I'm very impressed with how fast this whole setup can dump really huge pages.

I have only one last question 😅: is it possible somehow to make custom URLs for multiple slugs?
with some config file with strings like `"about": "12jhjkj4234jk;aowoq"`.
I read the brief documentation, please, point me if I missed something

**Comment by transitive-bullshit** [comment]
Should be very easy to setup; would you mind explaining your ideal use case a bit more in-depth so I can generalize it and add it to the repo?

**Comment by tiulpin** [comment]
My ideal use case: to have this map in a separate JSON, e.g. `.map.json`
```
{
    "about": "78fc5a4b88d74b0e824e29407e9f1ec1",
    "subscribe": "4e29407e9f1ec178fc5a4b88d74b0e",
    "socials": "b88d74b0e824e29b88d74b0e824e2"
}
```
Or just the same thing declared in `site.config.js` (but with the separated JSON it will be easier to parse with any tool)

**Comment by transitive-bullshit** [comment]
Added in b50d21c.

```js
{
  pageUrlOverrides: {
    '067dd719a912471ea9a3ac10710e7fdf': '/foo',
    '0be6efce9daf42688f65c76b89f8eb27': '/bar'
  }
}
```

Note that `site.config.js` is a JS file, so if you want to store this mapping in a separate JSON file so it's easy to generate, that's really easy. Just do:

```js
// top of site.config.js
const pageUrlOverrides = require('./page-overrides.json')

// and then use pageUrlOverrides in your config
```

**Comment by transitive-bullshit** [comment]
@tiulpin feel free to re-open if you run into any issues. The logic around mapping UUIDs and non-UUIDs is a bit error-prone in places, but I tried to make it pretty robust against invalid inputs.

**Comment by tiulpin** [comment]
Thanks for the updates, the configuration works (forked the repo and edited the config [here](https://github.com/tiulpin/nextjs-notion-starter-kit), but URLs are not overridden on generated pages

How to reproduce
- open the first link on https://experimenthoot.vercel.app
- see https://experimenthoot.vercel.app/5e528592a3ea4bef9253b7ddce6f0c62
- https://experimenthoot.vercel.app/about works if open directly, is it possible to redirect to that page?

**Comment by transitive-bullshit** [comment]
Hey @tiulpin, I think I fixed the issue now in https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/509e2631b8623baca725c54b66cf97916708ef89.

I also switched the URL mapping around, so it's now what you originally requested:

```json
{
  pageUrlOverrides: {
    '/foo': '067dd719a912471ea9a3ac10710e7fdf',
    '/bar': '0be6efce9daf42688f65c76b89f8eb27'
  }
}
```
