### ISSUE TITLE
TypeForm Doesn't Render

### ISSUE THREAD

**Issue by pavlovcik** [transitive-bullshit/nextjs-notion-starter-kit#47]
Not essential for my use case but figure I'd make you aware of this for the back log. Same issue as the nested todo items; the TypeForm element doesn't make it out the other side.

https://www.notion.so/Recruiting-ed22bd41190647bdaf8878fdf255be4b - do you have access to my notion?
https://dao.ubq.fi/recruiting

**Comment by transitive-bullshit** [comment]
Thanks for the issue, Alex.

Fixed in https://github.com/NotionX/react-notion-x/commit/1af66536afd85284b70e05cfb3116c098df5622a and should be available if you update to latest.
