### ISSUE TITLE
Seeing Double (Images)

### ISSUE THREAD

**Issue by pavlovcik** [transitive-bullshit/nextjs-notion-starter-kit#50]
https://www.notion.so/uAD-Token-2679c7cc6fd44a178bfe22c666c3501e
https://dao.ubq.fi/2679c7cc6fd44a178bfe22c666c3501e

We've got some comments and have since updated the image through our dialogue
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/107594089-b8a61e80-6bd6-11eb-99b1-c7320fa50336.png">

but on the rendered page it shows both version 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/107594132-d1aecf80-6bd6-11eb-8b0b-5561bc151fdf.png">

ser bls

**Comment by transitive-bullshit** [comment]
This is an interesting bug. I was able to reproduce the issue but wasn't able to figure out what's going on. Notion still shows the second image block; it's just empty, and there's nothing I could discern between these two blocks JSON data that would mean the second one shouldn't be displayed.

Weird.

**Comment by transitive-bullshit** [comment]
Closing for now, as I think we resolved it async.
