### ISSUE TITLE
TypeError: contentBlockIds.flatMap is not a function

### ISSUE THREAD

**Issue by pHequals7** [transitive-bullshit/nextjs-notion-starter-kit#52]
So I cloned this repo and did the usual npm install and npm run dev (thus the page would be directed to your default public page)

But as soon as it compiled and I tried loading localhost:3000 this error propped (see image below)

#
![notion_error](https://user-images.githubusercontent.com/39328505/107985319-e1bc1a00-6fef-11eb-83fd-2573f176074d.JPG)

Any kind of help would be appreciated!

My stack is 
Windows 10 and npm version of 6.9.0

**Comment by transitive-bullshit** [comment]
@pHequals7 you need to upgrade your version of node.js >= 12.
