### ISSUE TITLE
Support for Spotify Embed

### ISSUE THREAD

**Issue by pHequals7** [transitive-bullshit/nextjs-notion-starter-kit#54]
Hey, firstly thanks for this awesome repo!

I have few blog articles hosted on Notion that redirects to my personal domain which has certain Spotify embeds. But the react-notion-x renderer is not able to display them. Screenshots attached for reference.
![spot_notion](https://user-images.githubusercontent.com/39328505/108264132-2af5a080-718d-11eb-9e8f-ee0c5b26d5b6.JPG)
But this is how it looks on my notion doc
![spot2_notion](https://user-images.githubusercontent.com/39328505/108265098-5c22a080-718e-11eb-9a8b-1b60c6c0828d.JPG)

**Comment by transitive-bullshit** [comment]
Hey @pHequals7, please include a notion ID so I can repro your example :)

**Comment by transitive-bullshit** [comment]
Here is an example of a page using `react-notion-x` with a spotify embed https://react-notion-x-demo.transitivebullsh.it/embeds-5d4e290ca4604d8fb809af806a6c1749

So it's probably some detail around the type of spotify embed that I'll have to look into.

Thanks!

**Comment by pHequals7** [comment]
This is the public notion link for the same

https://www.notion.so/pranavhari/The-Highly-Opinionated-yet-Definitive-List-of-Best-Comic-Book-Movie-Background-Scores-07107ae6dcba498eba2ffa91d067aa84

**Comment by transitive-bullshit** [comment]
Thanks @pHequals7. This should now be fixed if you update to latest `react-notion-x`. 🙏
