### ISSUE TITLE
SpaceID does not work properly

### ISSUE THREAD

**Issue by emindeniz99** [transitive-bullshit/nextjs-notion-starter-kit#55]
I have set spaceID, but Notion’s help pages are rendered

https://emindeniz99.com/notion-help-e040febf70a94950b8620e6f00005004

https://emindeniz99.com/Privacy-afb514088138407893f9959d65dd9783

Thank you, it is good project :)
I have used frutionsite with notion, it was very heavy. 

Edit:
I have set wrong spaceid, it is solved :( sorry

**Comment by transitive-bullshit** [comment]
Huzzah 😄 

@emindeniz99 is there anything we could add to the docs to make the space ID easier to setup?
