### ISSUE TITLE
Image not making it out the other side again

### ISSUE THREAD

**Issue by pavlovcik** [transitive-bullshit/nextjs-notion-starter-kit#56]
https://www.notion.so/uAD-Token-2679c7cc6fd44a178bfe22c666c3501e
https://dao.ubq.fi/uad-token#851098f611b843a7b8a655c8d17d00c7

bls ser

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/108311699-114b5d80-717b-11eb-92f8-31db0e5c8363.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4975670/108311870-67b89c00-717b-11eb-9519-11487ce927a7.png">

**Comment by transitive-bullshit** [comment]
Thanks, Alex.

This should be fixed now if you update to latest. https://github.com/NotionX/react-notion-x/commit/36c75f970123aeefa6306775b667ffd219f572fd
