### ISSUE TITLE
Error:  Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by mattbratos** [transitive-bullshit/nextjs-notion-starter-kit#566]
Did everything like in Read me 

Fork 
npm install
npm run dev

and there is this issue 

<img width="994" alt="Screenshot 2023-11-20 at 23 51 11" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/123769299/c67679dc-e3a9-4f80-9afe-3164fa5ad4ae">

**Comment by mattbratos** [comment]
What's interesting is that on Vercel everything works well. But I can't run it locally( the same repo, the same version)

**Comment by mattbratos** [comment]
After
npm audit fix --force
I have this issue 

<img width="1042" alt="Screenshot 2023-11-21 at 00 13 36" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/123769299/2bc3deb9-b479-4c08-a71d-3b609f91ae19">

**Comment by amanintech** [comment]
Having the same issues.

**Comment by amanintech** [comment]
Update: Using yarn to build doesn't causes the issue

**Comment by yunzhongci** [comment]
遇到一样的问题

**Comment by SarthakT7** [comment]
Did anyone get a workaround? I am facing this issue as well

**Comment by onnimonni** [comment]
Can you try to update latest version in the `main` branch with the new and updated `react-notion-x` version of `7.0.1`?

Does the problem still persist for you?

**Comment by transitive-bullshit** [comment]
This should be fixed in the latest version. If not, please create a new issue with repro instructions.
