### ISSUE TITLE
Search isn't working with "npm run start"

### ISSUE THREAD

**Issue by NoverNobida** [transitive-bullshit/nextjs-notion-starter-kit#57]
I hosted nextjs-notion-starter-kit on my own server. 
```
git clone https://github.com/transitive-bullshit/nextjs-notion-starter-kit.git
cd nextjs-notion-starter-kit.git
npm install
npm run build
npm run start
```
site: https://n.nov.re/

But "search" doesn't work.

![image](https://user-images.githubusercontent.com/46912250/108674200-d604b200-751f-11eb-82e4-bd5036941bc3.png)

![image](https://user-images.githubusercontent.com/46912250/108674424-3693ef00-7520-11eb-8f27-558ea28c2f56.png)

![image](https://user-images.githubusercontent.com/46912250/108674493-53302700-7520-11eb-9749-5e390af0fd92.png)

**Comment by transitive-bullshit** [comment]
Hey @NoverNobida, you need to run `vercel dev` locally in order for the serverless functions like search to work.

Are you deploying to vercel?

**Comment by NoverNobida** [comment]
No. For some reasons, I couldn't connect to Vercel well, so I just deployed it locally on my server using `npm run build && npm run start` .

**Comment by transitive-bullshit** [comment]
@NoverNobida does search work if you run `vercel dev` instead of `npm run start`?

The serverless functions won't be picked up by `npm run start`.

**Comment by NoverNobida** [comment]
![image](https://user-images.githubusercontent.com/46912250/108798378-a9f13b80-75c8-11eb-801f-572ed9d7e829.png)
It forms `http://localhost:3000`, not `https://domain.xxx`. And using `vercel dev`, `.js` is so big. 
![image](https://user-images.githubusercontent.com/46912250/108798648-43b8e880-75c9-11eb-9d14-8a40955f4228.png)

**Comment by transitive-bullshit** [comment]
This is localhost and is meant for dev / debugging; don't worry about the sizes.

When you deploy on `vercel`, everything gets optimized.

**Comment by NoverNobida** [comment]
Thanks a lot!
Sorry for taking your time.
By the way, can you please tell me, how does your website proxy notion's pictures? I can't proxy most pictures in this way:[willnorris/imageproxy](https://github.com/willnorris/imageproxy).

**Comment by transitive-bullshit** [comment]
@NoverNobida no worries; please create a new issue if you want to ask a separate question.
