### ISSUE TITLE
[Question] Og image is empty when sharing url link

### ISSUE THREAD

**Issue by justakim12** [transitive-bullshit/nextjs-notion-starter-kit#615]
#### Description
- Hello, first of all thank you for creating this awesome project 👍 
- I've cloned the repository and was making some small tweaks when I ran into a problem where the `og:image` seems to show an empty image. 
- I think it has something to do with the `site.config.ts > domain` definition as your `og:image` seems to work. Do you know what might be the problem? My og: image url is currently `https://kyungil-davids-blog.vercel.app/api/social-image?id=e747c93fdc144b9ca6ecf3e634629085`

<img width="447" alt="image" src="https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/40204699/343a18d1-a9c0-4aa6-a643-0621080b18c5">

#### Notion Test Page ID
- `e747c93fdc144b9ca6ecf3e634629085`

**Comment by hi-pengyu** [comment]
❤️

**Comment by amanabdullayev** [comment]
hey, is there any could fix this?

I am also facing the same issue. When I checked logs on Vercel, I see that there is "Unauthorized" warnings appear every time I share the link:
![image](https://github.com/user-attachments/assets/80038d2b-7841-4b78-aed8-1c4f0ecde108)

**Comment by northcee** [comment]
Same issue! Please fix for this

**Comment by zodwick** [comment]
disabling vercel authentications as mentioned in https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998 fixed the issue for me

**Comment by amanabdullayev** [comment]
okay, actually I saw this solution https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998 before. But it did not work.
Now I figured it out that, once you disable the vercel authentication you need to redeploy the project so it gets effective. Thanks, it is working now!

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998 is also required on Vercel's side for the project to be public in order for social auth to work.

Examples:

- [nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44](https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44)
- [transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396](https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396)
