### ISSUE TITLE
How to make Website / blog SEO friendly?

### ISSUE THREAD

**Issue by Tirth27** [transitive-bullshit/nextjs-notion-starter-kit#63]
I found many Notion hosting tools like [Super.so](https://super.so/), [HostNotion](https://hostnotion.co/), but they are all paid. The main feature they provide is prettifying URL which is implemented using URL rewrite. So I found a free tool Fruition that can do URL rewrite for Notion. But the problem with [Fruition ](https://fruitionsite.com/)and other paid solutions are that they still serve content from Notion. 

However, is there any way to make it SEO friendly directly from the method we are using? 

Any help will be appreciated. 

Thank you, 
Tirth

**Comment by transitive-bullshit** [comment]
This is exactly the point of this project.

We're using the Notion API and rendering the content in a very similar way that Super.so does, but it's all free and open source.

You should have excellent SEO and page load speeds by using this project.

**Comment by Tirth27** [comment]
Gotcha! Cool Thanks. 
Closing the issues.
