### ISSUE TITLE
How do I disable the GitHub icon in the top right corner?

### ISSUE THREAD

**Issue by wajid-pro** [transitive-bullshit/nextjs-notion-starter-kit#631]
#### Description

How do I disable the GitHub icon in the top right corner?

The icon redirects to the `transitive-bullshit/nextjs-notion-starter-kit repository`. How can I disable or hide it?
#### Notion Test Page ID
![Screenshot 2024-08-27 220341](https://github.com/user-attachments/assets/81131ab3-bc1b-436b-bc6d-779c5f787ee0)

**Comment by EmirhanKarahan** [comment]
Search for  <GitHubShareButton /> inside the project and delete it from NotionPage.tsx. That's it.

**Comment by wajid-pro** [comment]
Thank You
