### ISSUE TITLE
ISR doesn't seem to work

### ISSUE THREAD

**Issue by chandragie** [transitive-bullshit/nextjs-notion-starter-kit#638]
#### Description

I noticed that ISR does not work after deploying, I'm on Vercel.

The build logs however says it's active:

![image](https://github.com/user-attachments/assets/e9d3c4f4-a82e-4f36-b38c-4a9f8e8ce823)

![image](https://github.com/user-attachments/assets/abf2c325-d380-468a-851f-401f6193a784)

However, once the app is deployed, the changes in Notion never applied. I tried changing the `revalidate` value but no luck.

**Comment by mabdullahabid** [comment]
Same issue here

**Comment by mabdullahabid** [comment]
I was thinking maybe we could add a manual revalidate in order to trigger revalidation instead of having to deploy every time.

**Comment by chandragie** [comment]
> I was thinking maybe we could add a manual revalidate in order to trigger revalidation instead of having to deploy every time.

did you get it working?

**Comment by mabdullahabid** [comment]
Yes, I feel like the issue is not with this repo. Its Vercel. I think for some odd reason the revalidate doesn't work on the free plans. It considers ISR pages as SSG and only rebuilds them at build time. When I deployed the same website on my own VPS, it seemed to revalidate correctly.

**Comment by chandragie** [comment]
> Yes, I feel like the issue is not with this repo. Its Vercel. I think for some odd reason the revalidate doesn't work on the free plans. It considers ISR pages as SSG and only rebuilds them at build time. When I deployed the same website on my own VPS, it seemed to revalidate correctly.

What? Really? I must be missing the updates. ISR seems supported in free plan in my first Next project in 2022. 
On Vercel, I always get the 500 error complaining about sharp packages. Duh

**Comment by chandragie** [comment]
@mabdullahabid it's working now.
So, apparently ISR didn't work because of `sharp` error on Vercel. Fixed it and now everything including ISR works.
Here how I solved the `sharp` problem: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/618#issuecomment-2442119220

Closing this issue now.
