### ISSUE TITLE
Social images are not being generated

### ISSUE THREAD

**Issue by jorgearuv** [transitive-bullshit/nextjs-notion-starter-kit#649]
#### Description

Social images are not being generated. I've tried with my personal website and with the example URL and seems that the og image library doesn't work.

![CleanShot 2024-11-04 at 00 33 24@2x](https://github.com/user-attachments/assets/09ee1ef7-8b3e-4f1d-84de-b8533f20e3d3)

```
[GET] /api/social-image?id=133ccbd7-685b-8039-ab45-c8a9e57faf2b reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
```

Additionally, seems that the fonts are not being loaded in `OGImage`, found these in the Logs:

```
TypeError: Fetch API cannot load: file:///vercel/path0/public/fonts/Inter-Regular.ttf
    at (node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/utils/timeout.js:12:0)
    at (node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/utils/timeout.js:4:0)
    at (node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:228:15)
    at (node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:18:0)
    at (node_modules/.pnpm/ky@1.7.2/node_modules/ky/distribution/core/Ky.js:185:0)
```

#### Notion Test Page ID
cce3a9ef1daa4924b0e6f02efea91121

**Comment by transitive-bullshit** [comment]
This should now be fixed if you pull latest.

Examples:

- https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=ca24be04-c161-415c-b5e4-015a6a9a7d44
- https://transitivebullsh.it/api/social-image?id=3db25f36-0b1c-4591-b3e9-50e39edfb396

**Comment by transitive-bullshit** [comment]
Make sure your Vercel settings aren't set to require auth as well, which will prevent social images from working properly (https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/437#issuecomment-1826206998).

**Comment by jorgearuv** [comment]
Thanks @transitive-bullshit!

Updated everything and seems pretty good everywhere.

Just a heads up, I have the Vercel's hobby plan and deploying the latest update with the two fonts throw this error:

```
Error: The Edge Function "api/social-image" size is 1.11 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size
```

I needed to remove the bold font to skip the error. Otherwise works fine, thanks for the update!

**Comment by transitive-bullshit** [comment]
@jorgearuv this should be fixed now https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/652
