### ISSUE TITLE
api/social-image is over the 1Mb limit in free version of Vercel

### ISSUE THREAD

**Issue by onnimonni** [transitive-bullshit/nextjs-notion-starter-kit#652]
#### Description

I merged the latest changes and fixes from the main branch today and hit following issue:
```
Error: The Edge Function "api/social-image" size is 1.11 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size
```

<img width="571" alt="Screenshot 2024-11-08 at 14 34 25" src="https://github.com/user-attachments/assets/9b472970-4cbd-474e-9e0e-22e28bf14316">

I can disable them from my site but I thought that you would want to know.

#### Notion Test Page ID

7875426197cf461698809def95960ebf

**Comment by onnimonni** [comment]
This seems to be happening because of bundling both `interSemiBoldFont` and `interRegularFont` fonts into the edge function.

I removed `interRegularFont` from my `api/social-image.ts` and it started to work again.

Maybe we could be able to live with just a bold font in the social images?

**Comment by transitive-bullshit** [comment]
Yeah, I think that's a good call to make sure it works for all users.

**Comment by transitive-bullshit** [comment]
I removed the regular font for now: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/172bd84f835fe6144ee9ecee5927ee820a24003a

**Comment by onnimonni** [comment]
Thanks, I'll close the issue too 👍
