### ISSUE TITLE
HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by Tirth27** [transitive-bullshit/nextjs-notion-starter-kit#69]
I want to enable preview image support, so I set up my firebase. And I have set credentials as follows:

# Firebase Config
![Firebase Setup](https://user-images.githubusercontent.com/39476447/110287018-f82b2380-8039-11eb-8700-47e82e044598.png)

# Internal Config
![.env File](https://user-images.githubusercontent.com/39476447/110287214-39233800-803a-11eb-8a05-faf86211f7e1.png)

# Getting Error
![Error](https://user-images.githubusercontent.com/39476447/110287354-72f43e80-803a-11eb-8a00-cd9ae37b158c.png)

# Console Log
[console_log.txt](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/files/6099576/console_log.txt)

What am I doing wrong which is throwing the error?

**Comment by transitive-bullshit** [comment]
Is this just running locally? What happens when you run `vercel dev`?

I'm seeing `createPreviewImage server-side` events which is a good things — it means your lambda to create the preview images is being called successfully.

I would try adding some more logging to `notion.ts` and re-running until you can better pinpoint where the 404 is coming from.

**Comment by Tirth27** [comment]
Yes I was running the code locally using `npm run dev`

However, the same error occurs when I try running `vercel dev`

# Firebase Output
![Firebase Output](https://user-images.githubusercontent.com/39476447/110385419-08cbb000-80b3-11eb-88c0-ff3ebb4eb030.png)

# Browser Output
![Browser Output](https://user-images.githubusercontent.com/39476447/110385533-2731ab80-80b3-11eb-8b62-891557d63681.png)

# Console Log
[vercel_dev_console_log.txt](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/files/6104318/vercel_dev_console_log.txt)

**Comment by guusyy** [comment]
Any update on this? I've run into the same problem.

**Comment by wzulfikar** [comment]
@guusyy in my case, it's returning 404 error because because it's pointing to non-existent endpoint. 

```typescript
// get-preview-images.ts#L42-L44
return got
  .post(api.createPreviewImage, { json })
  .json() as Promise<types.PreviewImage>
```

The `api.createPreviewImage` points to `localhost/api/...` which doesn't exist because the `api` folder was outside `pages`. So, I moved the api folder to `pages/api` and the endpoint is now detected by Next.js. Because the endpoint is now detected, the error disappears.

**Comment by Tirth27** [comment]
Hi @wzulfikar, If we move the `api` folder inside the `pages` folder, will it not break the code as it will not found the file which is in `api` folder. 

Do we also need to update the path? To where the new API folder is located? i.e `pages/api` instead of `api`?

**Comment by wzulfikar** [comment]
Yes, you need to update the import paths too

**Comment by wujunchuan** [comment]
> @guusyy in my case, it's returning 404 error because because it's pointing to non-existent endpoint.
> 
> ```ts
> // get-preview-images.ts#L42-L44
> return got
>   .post(api.createPreviewImage, { json })
>   .json() as Promise<types.PreviewImage>
> ```
> 
> The `api.createPreviewImage` points to `localhost/api/...` which doesn't exist because the `api` folder was outside `pages`. So, I moved the api folder to `pages/api` and the endpoint is now detected by Next.js. Because the endpoint is now detected, the error disappears.

It works for me. Just move ffolder to new place, and vscode will update import paths auto.

**Comment by guusyy** [comment]
> @guusyy in my case, it's returning 404 error because because it's pointing to non-existent endpoint.
> 
> ```ts
> // get-preview-images.ts#L42-L44
> return got
>   .post(api.createPreviewImage, { json })
>   .json() as Promise<types.PreviewImage>
> ```
> 
> The `api.createPreviewImage` points to `localhost/api/...` which doesn't exist because the `api` folder was outside `pages`. So, I moved the api folder to `pages/api` and the endpoint is now detected by Next.js. Because the endpoint is now detected, the error disappears.

Thanks alot! It woks now :)

**Comment by transitive-bullshit** [comment]
The latest release greatly simplifies how we're handling preview images.

No more separate api function to generate them. No more google firebase dependency.

**It just works by default.**

You can optionally enable redis caching if you want to speed up subsequent builds, but it's not required.
