### ISSUE TITLE
How can I get my own rootNotionSpaceId?

### ISSUE THREAD

**Issue by jorgeruvalcaba** [transitive-bullshit/nextjs-notion-starter-kit#71]
In the docs specify the steps for getting and setting up the rootNotionPageId but not sure how I can accomplish this for the workspace I'm using.

**Comment by transitive-bullshit** [comment]
https://github.com/transitive-bullshit/nextjs-notion-starter-kit/issues/38#issuecomment-771242532

**Comment by jorgeruvalcaba** [comment]
Great! I'll add it to the README
