### ISSUE TITLE
Overlapping Table of Content with Page text.

### ISSUE THREAD

**Issue by Tirth27** [transitive-bullshit/nextjs-notion-starter-kit#73]
Hi @transitive-bullshit , 

My text is overlapping with the TOC, do you have any idea how to resolve the issue? 

![image](https://user-images.githubusercontent.com/39476447/110907026-e9f24580-8360-11eb-87b1-afbb9e172c0a.png)

**Comment by killianhuyghe** [comment]
I was able to workaround the issue by tweaking the css.

You can add these lines at the end of `styles/notion.css`:
```
@media (min-width: 1300px) and (min-height: 300px) {
  .notion-page-content-has-aside {
    width: calc((100vw + var(--notion-max-width)) / 2 - 12px);
  }
}

@media (min-width: 1300px) and (min-height: 300px) {
  .notion-page-content-has-aside .notion-page-content-inner {
    width: calc(var(--notion-max-width) - 24px);
    max-width: calc(var(--notion-max-width) - 24px);
  }
}

.notion-aside {
  overflow-x: hidden;
  padding-left: 24px; /* Adjust the space between the main content and the table of content here */
}

.notion-aside-table-of-contents {
  width: 100%;
}

.notion-aside-table-of-contents .notion-table-of-contents-item-body {
  overflow: hidden;
  text-overflow: ellipsis;
}
```

**Comment by transitive-bullshit** [comment]
Ahhh yep; the sidenav ToC is a little hacky CSS-wise, and definitely doesn't deal with wider content very well.

@killianhuyghe thanks for posting your CSS tweak 😄

**Comment by killianhuyghe** [comment]
Sure thing!

FYI, I just edited `.notion-aside-table-of-contents` to use `max-width` instead of `width` to still allow shorter table of contents to be centered.

**Comment by Tirth27** [comment]
It works, Thank you @killianhuyghe :)

**Comment by dedfft** [comment]
> @media (min-width: 1300px) and (min-height: 300px) {
>   .notion-page-content-has-aside {
>     width: calc((100vw + var(--notion-max-width)) / 2 - 12px);
>   }
> }
> 
> @media (min-width: 1300px) and (min-height: 300px) {
>   .notion-page-content-has-aside .notion-page-content-inner {
>     width: calc(var(--notion-max-width) - 24px);
>     max-width: calc(var(--notion-max-width) - 24px);
>   }
> }
> 
> .notion-aside {
>   overflow-x: hidden;
>   padding-left: 24px; /* Adjust the space between the main content and the table of content here */
> }
> 
> .notion-aside-table-of-contents {
>   max-width: 100%;
> }
> 
> .notion-aside-table-of-contents .notion-table-of-contents-item-body {
>   overflow: hidden;
>   text-overflow: ellipsis;
> }

Could you please advise. I add your code to notion.css and they still do not overwrite the default( 
I reduce this value((
![image](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/43168887/8524e919-bed8-4658-86e2-122b91b6189e)

![image](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/assets/43168887/e8e82aca-e514-4e5f-abd2-f83c213b7722)
