### ISSUE TITLE
Error using search with "npm run dev"

### ISSUE THREAD

**Issue by max-pod** [transitive-bullshit/nextjs-notion-starter-kit#74]
![image](https://user-images.githubusercontent.com/63061392/110983941-6e7c9e00-8338-11eb-9855-8883970a49f8.png)

Replicate: git clone the starter-kit and attempt to search a random 2-letter combination while running npm run dev.

The error comes from search-notion.ts. After logging the response I got:
![image](https://user-images.githubusercontent.com/63061392/110984496-345fcc00-8339-11eb-9b8a-a95a0539e24e.png)

![image](https://user-images.githubusercontent.com/63061392/110984806-9fa99e00-8339-11eb-80a2-97d261f19765.png)

I have not gotten the search functionality to work in development, is it something that only works in build?

**Comment by transitive-bullshit** [comment]
> I have not gotten the search functionality to work in development, is it something that only works in build?

Run `vercel dev` to get the serverless functions to work in development.

**Comment by transitive-bullshit** [comment]
This is due to a bug in `next.js` which doesn't recognize certain serverless functions during dev, but if you use `vercel dev`, it'll work as expected.
