### ISSUE TITLE
Can't sync with Notion anymore ？

### ISSUE THREAD

**Issue by Jerrywang959** [transitive-bullshit/nextjs-notion-starter-kit#76]
First of all, thanks for your excellent work. 

I have been using this for serveral days. At first, when I change some content, to see the new content on  vercel, just press Ctrl+Shift+R. 

But now, it doesn't work. To see new content, I have to redeploy. Did I configure something wrong？ Or vercel had limited this？ I don't have an idea, so open this issue.

**Comment by Jerrywang959** [comment]
My repo 
https://github.com/Jerrywang959/notionsite

**Comment by Jerrywang959** [comment]
It's in sync again. That's weird

**Comment by transitive-bullshit** [comment]
Hey @Jerrywang959, I'm so glad that the issue resolved itself 😂 I had your issue open in a tab, but I wasn't sure how to respond since I have no idea what might've been going on.

Cheers 😄
