### ISSUE TITLE
Bug about math block(Both inline and block equation)

### ISSUE THREAD

**Issue by PowderHan** [transitive-bullshit/nextjs-notion-starter-kit#81]
Hello, this project is really great, Thank you very much!
But I got some bug about render equation(both inline equation and block equation).
Here is one example Notion page: https://www.notion.so/sylvan18/Activation-function-5bd1bd33678341f38265ae4a43e5dbf0

All math equation render with some bug, like this:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/46041980/113478359-f62e7600-94ba-11eb-815c-05818b4125cb.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/46041980/113478376-05adbf00-94bb-11eb-9cb7-ceb014300640.png">

Both the resource code and math style are displayed. This really affects blog's imporession. Hope it could be fixed. Thank you very much.

**Comment by transitive-bullshit** [comment]
Hey PowderHan, thanks for the feedback. Some blocks like math / katex are optional and need to be enabled.

For equations, have you added this to your app? (if using next.js, _app.js):

```
// used for rendering equations (optional)
import 'katex/dist/katex.min.css'
```

**Comment by PowderHan** [comment]
Hi, I forgot to uncomment this line. Now I solved it, thank you very much.
