### ISSUE TITLE
Cloudflare Pages Compatibility?

### ISSUE THREAD

**Issue by chof64** [transitive-bullshit/nextjs-notion-starter-kit#85]
Hello, I've came across with Cloudflare Pages while I was managing my domain, and it seems to be a good alternative service for Vercel.

I was woundering if this process is compatible with Cloudflare Pages? If not, have you taken a look of adding maybe a version that is compatible with Cloudflare Pages.
[https://pages.cloudflare.com/](https://pages.cloudflare.com/)

Thank You

**Comment by emindeniz99** [comment]
CF Pages are for static pages. So, it can not be used for serving next.js. Bu cloudflare workers are alternative to vercel for next.js.
But, "workers" does not support node.js, it uses v8 engine.

https://flareact.com/ is nextjs of workers :D
 but it is beta/alpha.

**Comment by chof64** [comment]
> CF Pages is for static pages. So, it can not be used for serving next.js. Bu cloudflare workers are alternative to vercel for next.js.
> But, "workers" does not support node.js, it uses v8 engine.
> 
> https://flareact.com/ is nextjs of workers :D
> but it is beta/alpha.

Oh, ok. thank you for the response. I'm just gonna close this thing then.

**Comment by transitive-bullshit** [comment]
Thanks @emindeniz99.

@chof64 you can also check out https://github.com/NotionX/react-notion-x which is what this template uses under the hood. It should be compatible with CF workers.

**Comment by chof64** [comment]
> Thanks @emindeniz99.
> 
> @chof64 you can also check out https://github.com/NotionX/react-notion-x which is what this template uses under the hood. It should be compatible with CF workers.

Ok, will take a closer look at it. But I've taken a look at it before, and honestly, I don't know the installation process of it. I'm still starting at this, and my knowledge is very limited at the moment.

**Comment by transitive-bullshit** [comment]
@chof64 no worries; I honestly think this would be a really great collaboration mashup if anyone in the community wants to lead it.

cc @lukeed who's been jamming on some next level Cloudflare workers stuff lately with https://github.com/lukeed/worktop

**Comment by lukeed** [comment]
Hey 👋  If you could forgo the continuously-dynamic aspect, I think you _could_ use Pages here. You would just have to trigger a new Pages build whenever your Notion content changes. It'd be tedious, but possible – but it's also a complete guess so don't take my word for it 😅

**Comment by emindeniz99** [comment]
non-static nextjs on cloudflare pages is very new feature. you can check the blog post that is published yesterday. https://blog.cloudflare.com/next-on-pages/
it uses different runtime( instead nodejs), so your compile error is normal :D
I did not read the blog post yet.
