### ISSUE TITLE
Can the article be paginated?

### ISSUE THREAD

**Issue by nodewey** [transitive-bullshit/nextjs-notion-starter-kit#86]
Hi，@transitive-bullshit 

If I add too many articles，all articles will be loaded.
Can the paging function of notion be retained?

![image](https://user-images.githubusercontent.com/51262212/114147768-9ec15780-994b-11eb-8904-88e902aba609.png)

**Comment by transitive-bullshit** [comment]
This is a great feature request for https://github.com/NotionX/react-notion-x.

For now, I'd recommend splitting them up into separate pages manually.

**Comment by nodewey** [comment]
> This is a great feature request for https://github.com/NotionX/react-notion-x.
> 
> For now, I'd recommend splitting them up into separate pages manually.
Thank you for your reply. What I want to ask is, will this feature be developed in the future?

**Comment by nodewey** [comment]
> This is a great feature request for https://github.com/NotionX/react-notion-x.
> 
> For now, I'd recommend splitting them up into separate pages manually.



Thank you for your reply. What I want to ask is, will this feature be developed in the future?

**Comment by transitive-bullshit** [comment]
I don't have any plans to implement it myself, but it's an open source project supported by the community for free. So if you want to add a feature, you're more than welcome to add it or incentivize others to add it :) :) :)

If you want to continue the conversation, please open a separate issue over on react-notion-x.

Thanks!
