### ISSUE TITLE
How to make Database Output Two Columns

### ISSUE THREAD

**Issue by chof64** [transitive-bullshit/nextjs-notion-starter-kit#88]
Hello, my notion site renders my Gallery Databases as only one column. How do I make it two column like the sample site?
![Screen Shot 2021-04-09 at 9 58 52 PM](https://user-images.githubusercontent.com/46257935/114191362-e6150b80-997e-11eb-871f-3c7c67cf7ac3.png)
I tried making the sizes small medium and large, but it just renders it as one column.

**Comment by transitive-bullshit** [comment]
You'll want to edit some of the CSS: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/transitive-bullshit/styles/notion.css#L42-L46

Note that it will default to 1 column on smaller screens.

Hope that helps.

**Comment by pzjzeason** [comment]
Maybe you've not set this gallery page as index page in `site.config.js `

**Comment by hh23485** [comment]
Also want to know about this, my page also only one column be default settings? even in the big screen. Do @transitive-bullshit use the default css?  How to make it as two? https://hh23485-notion-blog-5bpm8pw6c-hh23485.vercel.app/

![image](https://user-images.githubusercontent.com/14577931/160325438-acb48c3f-d4b0-488f-b1c1-f7a24ca23366.png)

not like yours

![image](https://user-images.githubusercontent.com/14577931/160325542-50c87f41-7817-41a5-a161-eaec1df461bd.png)

> You'll want to edit some of the CSS: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/transitive-bullshit/styles/notion.css#L42-L46
> 
> Note that it will default to 1 column on smaller screens.
> 
> Hope that helps.

**Comment by chiperman** [comment]
@hh23485 Try setting the page on Notion as a full-page will fix your problem.
