### ISSUE TITLE
How can I change the icon of this site?

### ISSUE THREAD

**Issue by JankinShaw** [transitive-bullshit/nextjs-notion-starter-kit#89]

**Comment by JankinShaw** [comment]
![图像2021-4-10 23 25](https://user-images.githubusercontent.com/82252520/114275307-9d2f8680-9a54-11eb-96f9-667e09ff8c35.jpeg)

**Comment by JankinShaw** [comment]
I'll appreciate it if you can give me an early reply!

**Comment by bcanata** [comment]
You can change 5 _favicon_ files in your fork's _public_ directory. There are services that lep ypu create those files in bulk. Also, as this is an _open source_, there's no meaning in asking for a _quick reply_.

**Comment by JankinShaw** [comment]
Appreciate it!!! @bcanata

**Comment by transitive-bullshit** [comment]
Thanks @bcanata; you can also just remove all these extra favicon files and replace the default favicon.ico / favicon.png.

Cheers.
