### ISSUE TITLE
'npm run build' can't generate dist files

### ISSUE THREAD

**Issue by greysonOuyang** [transitive-bullshit/nextjs-notion-starter-kit#90]
Hi, I tried to deploy it to My VPS. So I run 'npm run build' command, it doesn't occur error,but can't generate dist files. I would appreciate it if you could give me some advice.

**Comment by transitive-bullshit** [comment]
Can you run `npm run build` locally?

What is the error you're getting?

This project is optimized for deployment to Vercel. It doesn't sound like you're using Vercel, so unfortunately I won't be able to help you without more info.

**Comment by greysonOuyang** [comment]
> Can you run `npm run build` locally?
> 
> What is the error you're getting?
> 
> This project is optimized for deployment to Vercel. It doesn't sound like you're using Vercel, so unfortunately I won't be able to help you without more info.

Thank you very much. I deploy it to vercel now, that is now a question any more.

**Comment by minesunny** [comment]
it generates dist files,but it is generated by next, the directory is  called  '.next'.As you can see, it is a hidden directory
