### ISSUE TITLE
Notion's "Timeline - Inline" cannot be presented correctly here

### ISSUE THREAD

**Issue by JankinShaw** [transitive-bullshit/nextjs-notion-starter-kit#94]
<img width="808" alt="截屏2021-04-13 22 38 16" src="https://user-images.githubusercontent.com/82252520/114571062-f1cb3f80-9ca8-11eb-9b5e-1fb3164b84c0.png">
<img width="982" alt="截屏2021-04-13 22 39 16" src="https://user-images.githubusercontent.com/82252520/114571225-158e8580-9ca9-11eb-93f7-961f21febc20.png">

**Comment by transitive-bullshit** [comment]
Hey @JankinShaw, welcome 👋

This is a feature request for https://github.com/NotionX/react-notion-x which doesn't support timeline views at the moment.

Please create a separate issue over there to track support.

Thanks!
