### ISSUE TITLE
about questions search

### ISSUE THREAD

**Issue by onemonet** [transitive-bullshit/nextjs-notion-starter-kit#95]
Can search be added to the mobile phone?
Computer search is extremely slow, and sometimes it can’t be found.
Thanks!

**Comment by transitive-bullshit** [comment]
Hey @onemonet, we're using notion's built-in search to power our search.

This is a lot easier than having our own search index, but it's not always performant.

Ideas to improve features like search are more than welcome :)

**Comment by wz1616** [comment]
I have the problem too.
Please improve search

**Comment by transitive-bullshit** [comment]
Search has been fixed in the latest release.

Hopefully it won't be as brittle anymore.
