### ISSUE TITLE
how to override url to use only notion page id, and not page title

### ISSUE THREAD

**Issue by chof64** [transitive-bullshit/nextjs-notion-starter-kit#99]
Hello, is there a way to make the page URL from using Page name, and instead, make it to use only notion page id.
From: `www.example.com/a-sample-page`
To: `www.example.com/f4784bn9m312m`

Thanks.

**Comment by transitive-bullshit** [comment]
Set `includeNotionIdInUrls: true` in `site.config.js`

**Comment by chof64** [comment]
> Set `includeNotionIdInUrls: true` in `site.config.js`

Worked thanks.
